로또 1단계 미션 제출합니다.
next-step/java-lotto-kakao pull request #23
Opened 2024-04-02 09:37 UTC by RyooChan

2024-04-03 12:51 UTC, seokhong requested changes
류찬님 안녕하세요.
로또 미션을 함께 진행할 리뷰어 김석홍입니다. 만나서 반갑습니다!

코멘트 남긴 내용 확인 부탁드립니다.
코멘트 관련하여 궁금하신 점은 PR에 코멘트 또는 슬랙으로 DM 보내주시면 확인하는대로 회신 드리겠습니다. 🙂

2024-04-03 12:51 UTC, seokhong commented on src/main/java/LottoController.java
> +    private static Amount getAmount() {
메서드의 배치는 어떤 순서로 하시나요? :)

2024-04-03 12:51 UTC, seokhong commented on src/main/java/model/Amount.java
> +        if (cost % 1000 != 0) {
1000이라는 값이 상수로 정의되어 있으니, 상수를 활용해보면 어떨까요?

2024-04-03 12:51 UTC, seokhong commented on src/main/java/model/Ball.java
> +import static model.random.NumberRange.END;
1, 45라는 값을 enum 으로 정의하신 이유가 있을까요?
`Ball`은 로또에서 1개의 번호를 관리하는 클래스로 보이며, 이 볼은 1-45 사이의 값만을 가질 수 있으니, 볼이 직접 관련된 숫자를 가지고 있는 건 어떨까요?

2024-04-03 12:51 UTC, seokhong commented on src/main/java/model/Ball.java
> +public class Ball {
숫자를 관리하는 클래스 좋습니다. 👍 
로또 번호에서 1이라는 값은 항상 동일한 의미를 가질 것으로 보여요. 그렇다면 각 숫자에 대해 하나의 객체를 만들어서 재사용하는 건 어떨까요?
현재는 로또를 많이 구매할 수록 `Ball`이 많이 생성될텐데, 매우 많은 수의 객체를 만든다면 메모리 측면에서 단점이 있지는 않을까요?

2024-04-03 12:51 UTC, seokhong commented on src/main/java/model/calculator/LottoResult.java
> +    public void saveRanking(Lottery lottery) {
코드를 봤을 때, `LottoResult`를 생성한 후 `saveRanking`이 호출되기 전까지 `ranking`은 사용하면 안되는 값으로 보입니다.
또한 `Calculator`도 적절한 메서드의 호출이 있기 전에는 결과를 조회할 경우 유효하지 않은 값을 반환하겠죠.

객체가 생성된 이후에는 어느 시점에 메서드가 호출되든 유효한 값을 사용할 수 있도록 구현해 보시면 좋겠습니다.
예를 들면, 등수를 미리 계산한 후 `LottoResult`를 만든다면, `LottoResult`를 사용하는 입장에서는 어느 시점에든 원하는 메서드를 호출하면 원하는 결과를 얻을 것이라고 생각할 수 있겠죠. 즉, 메서드의 호출 순서나 구체적인 사용법을 몰라도 안전하게 사용할 수 있습니다.
객체를 사용하기 위해 클래스의 내부 구현을 자세히 알아야 한다면, 이는 클래스의 캡슐화가 안 된 것일수도 있고, 클래스 간의 결합도가 강한 것일 수도 있습니다.

2024-04-03 12:51 UTC, seokhong commented on src/main/java/model/random/LottoNumbers.java
> +
불필요한 빈 줄이 추가된 것으로 보이네요!

2024-04-03 12:51 UTC, seokhong commented on src/main/java/model/random/LottoNumbers.java
> +    public static Set<Ball> generateRandNums(RandomNumberGenerator randomNumberGenerator) {
`Rand`, `Nums` 등은 무슨 단어의 약어인지 코드를 보면 바로 알 수 있지만, 그럼에도 약어를 사용하시지 않는 것을 추천합니다.
코드의 양이 많아지면 IDE의 문자열 검색 기능도 많이 사용하실텐데요. 이때, 약어는 제대로 검색이 안 되는 경우가 있습니다. 또한, 코드를 읽는 입장에서는 무슨 단어의 약어인지 한 차례 더 생각하는 것이 필요합니다. 구체적인 약어 사용 규칙이 있지 않다면, 항상 원래 단어를 그대로 사용하시는 것을 추천합니다.

2024-04-03 12:51 UTC, seokhong commented on src/main/java/model/random/LottoNumbers.java
> +public class LottoNumbers {
이 클래스는 무슨 목적으로 사용되는 클래스인가요?
6개의 번호로 구성되어야 하는 로또를 나타내는 객체라면, 검증을 하는 책임도 함께 가져보면 어떨까요?

2024-04-03 12:51 UTC, seokhong commented on src/main/java/model/random/RandomNumberGenerator.java
> +public interface RandomNumberGenerator {
항상 `Ball`을 생성해야 하는 것이라면, `Integer` 배열을 가지고 있기보다는 `Ball` 목록을 가지고 있고, 이를 이용해 값을 생성해도 괜찮지 않을까요?
생성 가능한 `Ball`의 목록은 `Ball`이 제공해 줄 수도 있겠네요!

2024-04-03 12:51 UTC, seokhong commented on src/main/java/model/winningLottery/Lottery.java
> +public class Lottery {
이름만 봤을 때는 고객이 구매한 복권처럼 보이는데, 실제로는 우승 번호를 관리하는 클래스로 보이네요.
더 적절한 이름은 없을까요?

2024-04-03 12:51 UTC, seokhong commented on src/main/java/model/winningLottery/Lottery.java
> +    public Ranking rank(LottoNumbers lottoNumbers) {
등수를 관리하는 `Ranking` enum 이 있으니, enum 의 각 객체가 당첨 여부를 판단하도록 구현해보면 어떨까요?
예를 들면 `Ranking.of(winningCount, isBonusMatched)`와 같이 사용할 수 있으면 어떨까요?

2024-04-03 12:51 UTC, seokhong commented on src/main/java/model/winningLottery/Ranking.java
> +    FIRST("6개 일치", 2000000000),
6개 일치했을 때의 도메인에서의 의미를 나타내는 네이밍 좋습니다. 👍 

다만, 가지고 있는 문자열은 콘솔 화면에 출력을 위한 내용처럼 보이기도 하네요.
화면에 출력하기 위한 내용은 뷰에 구현해보면 어떨까요?

2024-04-03 12:51 UTC, seokhong commented on src/main/java/model/winningLottery/WinningNumbers.java
> +public class WinningNumbers {
`WinningNumbers`는 `LottoNumbers`와 동일한 제약 규칙을 가질 것처럼 보이네요.
`LottoNumbers`를 그대로 활용할 수 있는 방법은 없을까요?

2024-04-03 12:51 UTC, seokhong commented on src/main/java/model/winningLottery/WinningBonusNumber.java
> +public class WinningBonusNumber {
보너스 볼이 우승 번호와 겹치지 않아야 한다는 것은 `WinningNumbers`와 `WinningBonusNumber`의 관계 하에서 지켜져야 할 규칙으로 보여요. 이는 `Lottery`에서 잘 검증할 수 있는 부분은 아닐까요? `Lottery`가 두 필드를 모두 알고 있으니, 두 필드가 지켜야 할 제약 조건도 알 수 있을 것 같아요. :)

2024-04-03 12:51 UTC, seokhong commented on src/main/java/view/OutputView.java
> +        System.out.printf("총 수익률은 %.2f입니다.", profitRate);
수익률이 1보다 작을 때 출력되어야 할 문구가 누락된 것으로 보이네요!

2024-04-03 12:51 UTC, seokhong commented on src/test/java/model/calculator/CalculatorTest.java
> +}
파일 마지막에 newline 이 없다고 깃헙에서 경고를 띄워주네요.  
파일 마지막의 newline 은 무슨 역할을 하는지 학습해보신 후, IDE 설정을 통해 휴먼 에러를 방지해보시면 좋겠습니다.

2024-04-03 12:51 UTC, seokhong commented on src/test/java/model/calculator/CalculatorTest.java
> +    void 로또번호들을_저장한다() {
여기에서 검증하는 내용이 값을 저장할 수 있는지일까요? 우승 번호와 6개가 일치하면 1등이라는 것을 검증하는 것처럼 보이기도 하네요!

2024-04-03 12:51 UTC, seokhong commented on src/main/java/model/random/LottoGenerator.java
> +    private final List<LottoNumbers> lottoNumberList;
생성한 로또를 필드로 가지고 있을 필요가 있을까요?
그대로 값을 반환해도 괜찮지 않을까요?

2024-04-03 12:51 UTC, seokhong commented on src/test/java/model/winningLottery/LotteryTest.java
> +class LotteryTest {
로또의 등수는 우승 번호와 일치하는 개수, 보너스 번호 일치 여부에 따라 결정되는데요.
그렇다면 0-6개의 우승 번호 일치, 각 상황에 대해 보너스 번호 일치/미일치를 검증하면 모든 케이스를 검증할 수 있지 않을까요?

2024-04-04 01:56 UTC, RyooChan commented on src/main/java/LottoController.java
> +    private static Amount getAmount() {
따로 순서는 없긴 한데, 나타나는 순서로 변경했습니다.
변경하는김에 기존 메서드들에서 getter랑 equalsAndHashCode 위치도 변경했습니다 :)

[2e46092](https://github.com/next-step/java-lotto-kakao/pull/23/commits/2e46092c56be59aa4b219f3d8ab63e5bad38a166)

2024-04-04 01:57 UTC, RyooChan commented on src/main/java/model/Amount.java
> +        if (cost % 1000 != 0) {
요거는 만들어두고 놓쳤네요 감사합니다~!

[4775639](https://github.com/next-step/java-lotto-kakao/pull/23/commits/47756399cd44e413486239c6f74c70b055e7f2b6)

2024-04-04 01:58 UTC, RyooChan commented on src/main/java/model/Ball.java
> +import static model.random.NumberRange.END;
따로 없기는 한데 여기저기 쓰일 것 같아 Enum으로 정의했었습니다.
Ball에 전체 로직을 적용시켜 이를 제거하고 볼에 정의했습니다~!

[f9db493](https://github.com/next-step/java-lotto-kakao/pull/23/commits/f9db493bdd516a726dae094a95a97cdc988dc558)

2024-04-04 01:59 UTC, RyooChan commented on src/main/java/model/Ball.java
> +public class Ball {
List를 통해 작성하였습니다. Map을 사용하면 Random num list를 만들 때에 key를 또 다시 셔플하는 번거로움이 있어 List를 사용했고, throw exception 로직도 변경했습니다~

[f9db493](https://github.com/next-step/java-lotto-kakao/pull/23/commits/f9db493bdd516a726dae094a95a97cdc988dc558)

2024-04-04 02:58 UTC, RyooChan commented on src/main/java/model/calculator/LottoResult.java
> +    public void saveRanking(Lottery lottery) {
말씀해주신대로 조금 결합도가 높은 방식으로 되어있던 것 같습니다.
static을 최대한 사용하지 않도록 개발하려고 하다 이상한 코드가 된 것 같아, 전체를 static을 활용하여 생성과 동시에 초기화되도록 변경했습니다. ^~^

[a9d748c](https://github.com/next-step/java-lotto-kakao/pull/23/commits/a9d748cbcdba1a1df696f968f979b9676dfc7c20)

2024-04-04 03:50 UTC, RyooChan commented on src/main/java/model/random/LottoNumbers.java
> +    public static Set<Ball> generateRandNums(RandomNumberGenerator randomNumberGenerator) {
약어를 정식 이름으로 변경했습니다~

[8048907](https://github.com/next-step/java-lotto-kakao/pull/23/commits/8048907b59626a396984a43b3b5f2aeedef77934)

2024-04-04 04:13 UTC, RyooChan commented on src/main/java/model/random/LottoNumbers.java
> +public class LottoNumbers {
요거는 랜덤으로 돌아간 로또 번호들이 저장되는 곳입니다.
유저가 입력하는 `지난주 당첨번호` 인 `WinningNumbers` 에만 validate 로직이 있으면 될 것 같아 검증은 그곳에만 작성해 두었습니다~!

2024-04-04 04:13 UTC, RyooChan commented on src/main/java/model/random/RandomNumberGenerator.java
> +public interface RandomNumberGenerator {
Ball에 해당 기능들 넣어 두었습니다!

[f9db493](https://github.com/next-step/java-lotto-kakao/pull/23/commits/f9db493bdd516a726dae094a95a97cdc988dc558)

2024-04-04 05:13 UTC, RyooChan commented on src/main/java/model/random/LottoGenerator.java
> +    private final List<LottoNumbers> lottoNumberList;
사실 바로 반환해도 상관없기는 한데, 로또를 몇개 만들지, 그리고 그 갯수에 대한 확인에 대한 로직 검즘을 위해 나누어 처리했습니다~

2024-04-04 05:15 UTC, RyooChan commented on src/main/java/model/winningLottery/Lottery.java
> +public class Lottery {
메서드명을 `winMatch` 로 변경했습니다.

2024-04-04 05:20 UTC, RyooChan commented on src/main/java/model/winningLottery/Lottery.java
> +    public Ranking rank(LottoNumbers lottoNumbers) {
해당 내용과 밑의 코드를 작성하면서 조금 고민이 많았는데요, 처음에는`Ranking`객체에 당첨을 위해 필요한 `WinningNubers` `WinningBonusMatch` 두개를 가지고 이를 통해 검증 및 출력하고자 했습니다.

ex) FIRST(6, false, 2000000000), SECOND(5, true, 30000000), THIRD(5, false, ...) ...
그런데 구현하면서

1. 사실상 Bonus match는 2등과 3등 로직에서만 사용되고 나머지에서는 false/true 상관없는데 이렇게 하는게 맞을까?
2. WinMatch -> 나머지 확인 -> 보너스번호가 사용되는 객체들만 WinningBonusNumber에서 검증 의 방식이 조금 더 알아보기 편할 것 같은데 이를 Enum에서 처리하는게 맞을까??

이런 생각이 들어서 아예 Enum은 데이터의 상태값만을 가지고 객체에서 검증을 하려고 했는데요, 혹시 리뷰어님은 어떻게 생각하실지 궁금합니다~!

2024-04-04 05:39 UTC, RyooChan commented on src/test/java/model/calculator/CalculatorTest.java
> +    void 로또번호들을_저장한다() {
요거 그냥 없어도 되는 테스트인것 같아 제거했습니다~

[0be0f4f](https://github.com/next-step/java-lotto-kakao/pull/23/commits/0be0f4fabc1b0f185c3ce14374b325a06b98de70)

2024-04-04 05:40 UTC, RyooChan commented on src/main/java/model/winningLottery/WinningBonusNumber.java
> +public class WinningBonusNumber {
검증 로직을 `Lottery` -> `WinMatch` 로 이동시켰습니다!
이렇게 바꾸니까 훨씬 보기 깔끔하네요:)

[0be0f4f](https://github.com/next-step/java-lotto-kakao/pull/23/commits/0be0f4fabc1b0f185c3ce14374b325a06b98de70)

2024-04-04 05:43 UTC, RyooChan commented on src/test/java/model/winningLottery/LotteryTest.java
> +class LotteryTest {
모든 당첨 케이스 확인 테스트케이스 추가했습니다~

[abe4461](https://github.com/next-step/java-lotto-kakao/pull/23/commits/abe44619c41b263117531134422e8adde86057e1)

2024-04-04 05:49 UTC, RyooChan commented on src/main/java/model/winningLottery/WinningNumbers.java
> +public class WinningNumbers {
제 생각은 `WinningNumbers`와 `LottoNumbers`가 다른 역할을 한다는 느낌이 들었습니다.
6개의 숫자를 받는것은 같지만, `LottoNumbers`는 자동 생성된 숫자들을 가지고 `WinningNumbers`같은 경우는 유저가 입력하는 방식이며 실제로 `LottoNumbers`의 검증에 `WinningNumbers` 와 `WinningBonusNumber` 모두가 사용되기 때문에 둘의 역할을 헷갈리는 경우를 방지하고자 아예 List<Ball> 을 받도록 작성했습니다~!

2024-04-04 05:51 UTC, RyooChan commented on src/test/java/model/calculator/CalculatorTest.java
> +}
<img width="637" alt="image" src="https://github.com/next-step/java-lotto-kakao/assets/53744363/3a84b7d4-dc51-418f-a003-8b3d047d9b95">

추가했습니다!

2024-04-04 05:55 UTC, RyooChan commented on src/main/java/view/OutputView.java
> +        System.out.printf("총 수익률은 %.2f입니다.", profitRate);
수익률에 대해 설명하는 것이라 생각해서 저부분을 작성을 안했었네요;
크게 중요한 로직은 아니라 생각해서 View에 작성해 두었습니다!

[61f92ef](https://github.com/next-step/java-lotto-kakao/pull/23/commits/61f92ef40af70740bbfcb8d2f3afff3c37eae0a3)

2024-04-04 08:56 UTC, seokhong commented on src/main/java/LottoController.java
> +    private static Amount getAmount() {
메서드 배치 순서에 따라서도 코드의 가독성이 달라지는데요. 관련해서 클린 코드의 메서드 배치 순서를 참고해 보셔도 좋겠습니다.
또한, 대개 toString, equals, hashCode, getter, setter 는 다른 메서드의 배치 후 가장 하단에 배치합니다. :)

2024-04-04 09:29 UTC, seokhong requested changes
류찬님 안녕하세요. 1단계 미션 코멘트 잘 반영하셨습니다. 👍 
질문 남겨주신 내용에 대한 답변과 함께 추가로 고민해보시면 좋을 것 같은 내용을 코멘트로 남겼습니다.
코멘트 확인 부탁드립니다. 🙂

2024-04-04 09:29 UTC, seokhong commented on src/main/java/model/Ball.java
> +    public static Ball createBallOrThrowException(int ballNumber) {
모든 메서드는 예외를 발생시킬 수 있으므로 `OrThrowException` 이라는 내용은 없어도 괜찮을 것 같습니다. :)
구현하는 코드에서 직접 예외를 발생시키지 않더라도, 사용하는 다른 코드에서 예외를 발생시킬 수도 있습니다.
스트림의 `orElseThrow`는 명시적으로 값을 조회하고 없는 경우 발생시킬 예외에 대한 처리를 인자로 받으므로, 기능을 서술한 이름으로 봐야 할 것 같습니다.

2024-04-04 09:29 UTC, seokhong commented on src/main/java/model/Ball.java
> +    public static List<Ball> lottoNums = IntStream.rangeClosed(START_NUMBER, END_NUMBER).mapToObj(Ball::new).collect(toList());
객체를 미리 만들어서 리스트로 저장하고 재사용하신 것 좋습니다. 👍 
성능 측면에서 조금 고민해본다면, `ArrayList`를 활용하고 (요청한 값 - 1) 위치의 객체를 반환하면 시간 복잡도 O(1)으로 객체를 조회할 수 있을 것으로 보이네요. :)

2024-04-04 09:29 UTC, seokhong commented on src/main/java/model/calculator/Calculator.java
> +    private final List<LottoResult> lottoResultList;
변수의 이름에 구체적인 컬렉션의 타입(e.g.,`Set`,`List`)은 사용하시지 않는 것을 추천합니다.  
리팩터링 과정에서 타입이 변경되기도 하는데, 이때 이름도 함께 변경해줘야 해서 비용이 추가로 발생합니다.  
`lottoResults`와 같은 이름을 사용해보는 건 어떨까요?

2024-04-04 09:29 UTC, seokhong commented on src/main/java/model/calculator/Calculator.java
> +    public static Calculator createCalculator(List<LottoResult> lottoResultList, WinMatch winMatch) {
`Calculator` 객체를 생성하는 시점에 바로 결과를 계산해야 할 필요가 있을까요?
메서드의 인자로 `lottos` 와 `WinMatch`를 받아서 당첨 결과(등수와 개수 - `rankingCountMap`, 구매한 로또 개수)를 반환하면 당첨 결과 객체를 외부에서 사용할 수 있지는 않을까요?
`Calculator`는 계산기라는 객체로 보이는데, 당첨 결과를 상태로 유지해야 할 필요가 있을지 고민되네요. 🤔 

로또의 흐름을 간단히 보면 아래와 같은데, 등수를 처리하는 코드의 복잡도를 좀 더 단순하게 가져갈 방법을 고민해 보셔도 좋겠습니다.
```
// 로또를 구매한다.
// 당첨 번호를 입력 받는다.
// 당첨 번호와 로또를 이용해서, 각 로또의 등수를 확인한다.
// 등수별로 당첨 수량을 모은다.
// 당첨 결과를 출력한다.
```

2024-04-04 09:29 UTC, seokhong commented on src/main/java/model/random/LottoNumbers.java
> +public class LottoNumbers {
랜덤으로 생성한 로또 번호에 버그가 있어서 7개 이상의 번호를 이용해 `LottoNumbers`를 만들면 어떻게 될까요?
이 객체를 사용하는 곳이 현재의 코드가 아니라, 추후 다른 코드가 생성되거나 내가 모르는 누군가가 이 객체를 사용할 수 있다고 상상하고 구현해 보시면 좋겠습니다. `LottoNumbers`가 6개의 숫자로만 구성되어 있어야 한다면, 이는 `LottoNumbers`가 지켜야 할 제약 조건이므로 항상 검증이 필요하다고 생각합니다. :)

2024-04-04 09:29 UTC, seokhong commented on src/main/java/model/random/RandomNumberGenerator.java
> +public interface RandomNumberGenerator {
`lottoNums`라는 필드를 그대로 노출하지 말고, `allBalls()`, `allLottoNumbers()` 등의 메서드로 제공해보면 어떨까요?
1. static 변수는 여러 스레드에서 동시에 접근/수정하는 경우 스레드 경합에 의한 버그가 발생할 위험이 있습니다.
2. 원본 데이터를 외부에서 접근하도록 열어 놓으면, 원본 데이터를 외부에서 임의로 변경하여 버그가 발생할 위험이 있습니다.
3. 메서드로 감싸서 제공하면, 필요에 의해 `lottoNums`의 구현이 달라지더라도 이를 사용하는 코드에는 변경이 불필요 합니다.

또한 `lottoNums`에 약어가 사용됐는데, 전체적으로 약어를 사용하는 코드를 확인해 보시면 좋겠습니다. :)

2024-04-04 09:29 UTC, seokhong commented on src/main/java/model/winningLottery/Ranking.java
> +    FIRST("6개 일치", 2000000000),
이 코멘트에 대해서는 어떤 의견이신가요? :)

2024-04-04 09:29 UTC, seokhong commented on src/main/java/model/winningLottery/WinningNumbers.java
> +public class WinningNumbers {
특정 클래스를 구현할 때, 이 클래스를 사용하는 곳의 코드에 대한 가정을 하지 않는 것이 좋습니다.
`LottoNumbers`에 남긴 코멘트를 참고해 보시면 좋겠습니다. :)

2024-04-04 09:29 UTC, seokhong commented on src/main/java/view/OutputView.java
> +        System.out.printf("총 수익률은 %.2f입니다.", profitRate);
수익률 기준으로 문구 추가 좋습니다. 👍 
코드의 중요도에 따른 클래스의 배치보다는, 이 코드가 도메인의 역할인지 화면의 역할인지를 기준으로 고민해 보시면 더 도움이 될 것 같습니다.

2024-04-04 09:29 UTC, seokhong commented on src/main/java/model/random/LottoGenerator.java
> +    private final List<LottoNumbers> lottoNumberList;
이렇게 구현하는 경우 `LottoGenerator`는 로또를 발급하고 싶을 때마다 매번 `LottoGenerator`를 생성해야 할 것으로 보여요.
로또 생성기인데, 매번 `LottoGenerator`를 생성하는 것은 비효율적이지 않을까요? 또한 필드는 상태를 나타내는데, 생성기의 상태로 발급한 로또를 관리해야 할 필요가 있을까요?
말씀하신 목적이라면, `Lotto`와 같은 클래스를 만들어서 N개의 `LottoNumbers`를 관리하도록 해보는 건 어떨까요? `LottoGenerator` 에서는 항상 `Lotto`를 생성해서 반환하도록 구현할 수도 있어 보이네요.

2024-04-04 09:46 UTC, RyooChan commented on src/main/java/model/winningLottery/Ranking.java
> +    FIRST("6개 일치", 2000000000),
@seokhong
해당 부분은 위의 질문과 연관되는 내용인데, 
<img width="781" alt="image" src="https://github.com/next-step/java-lotto-kakao/assets/53744363/927ef886-d486-477b-acfc-786ee94c2e9e">

요거를 변경해야 하면 동일하게 아예 value만 두고 이를 view 에서 합칠까 하긴 했습니다!
혹시 위의 방법은 어떻게 생각하실까요??

2024-04-04 12:19 UTC, seokhongkim commented on src/main/java/model/winningLottery/Lottery.java
> +    public Ranking rank(LottoNumbers lottoNumbers) {
결론부터 말씀드리면, 저는 `Ranking` 하나로 구현을 할 것 같습니다.
1. 2등과 3등 로직에서만 사용하더라도, 등수를 판단하기 위해 중요한 값이므로 `Ranking` 에서 인자로 받는 것이 자연스럽다고 생각합니다.
2. 현재의 구조에서는 `Ranking` 에 대한 정책이 변경될 경우, `Ranking` 과 `WinMatch` 두 코드의 변경이 모두 필요합니다. 둘 중 한 곳의 클래스가 변경될 때 다른 클래스도 반드시 변경이 필요하다면, 강한 결합을 가지고 있는 것이고, 이는 설계를 고민해봐야 한다는 신호라고 생각합니다.
3. enum 도 객체인데, 상태값만 가지고 있다면 객체라고 할 수 있을까요? 자동차 미션을 진행하며 객체에서 값을 꺼내지 않고 요청하는 형태로 구현하는 연습을 하셨을 것 같습니다. enum 도 객체라면, 상태 값을 가지고 있고 꺼내서 사용하는 것이 아니라, enum 에게 요청하는 형태로 구현해보면 어떨까요?

2024-04-04 12:21 UTC, seokhong reviewed
코멘트를 추가했습니다. :)

2024-04-04 12:21 UTC, seokhong commented on src/main/java/model/winningLottery/Lottery.java
> +    public Ranking rank(LottoNumbers lottoNumbers) {
결론부터 말씀드리면, 저는 `Ranking` 하나로 구현을 할 것 같습니다.
1. 2등과 3등 로직에서만 사용하더라도, 등수를 판단하기 위해 중요한 값이므로 `Ranking` 에서 인자로 받는 것이 자연스럽다고 생각합니다.
2. 현재의 구조에서는 `Ranking` 에 대한 정책이 변경될 경우, `Ranking` 과 `WinMatch` 두 코드의 변경이 모두 필요합니다. 둘 중 한 곳의 클래스가 변경될 때 다른 클래스도 반드시 변경이 필요하다면, 강한 결합을 가지고 있는 것이고, 이는 설계를 고민해봐야 한다는 신호라고 생각합니다.
3. enum 도 객체인데, 상태값만 가지고 있다면 객체라고 할 수 있을까요? 자동차 미션을 진행하며 객체에서 값을 꺼내지 않고 요청하는 형태로 구현하는 연습을 하셨을 것 같습니다. enum 도 객체라면, 상태 값을 가지고 있고 꺼내서 사용하는 것이 아니라, enum 에게 요청하는 형태로 구현해보면 어떨까요?

2024-04-04 15:41 UTC, RyooChan commented on src/main/java/model/Ball.java
> +    public static List<Ball> lottoNums = IntStream.rangeClosed(START_NUMBER, END_NUMBER).mapToObj(Ball::new).collect(toList());
람다식에 뭔가 정신이 팔려서 구현했었는데, 사실 변경하는편이 더 성능도 좋고 보기도 편할 것 같습니다.
get과 범위 기반 validate로 변경했습니다~!

[8776a9d](https://github.com/next-step/java-lotto-kakao/pull/23/commits/8776a9db1589f156193109a0b1eed9876d6fcf20)

2024-04-04 15:41 UTC, RyooChan commented on src/main/java/model/Ball.java
> +    public static Ball createBallOrThrowException(int ballNumber) {
메서드명 변경했습니다!

[a2407af](https://github.com/next-step/java-lotto-kakao/pull/23/commits/a2407af34177d8f79bc140bf419cfc62b95df8af)

2024-04-04 15:42 UTC, RyooChan commented on src/main/java/model/calculator/Calculator.java
> +    private final List<LottoResult> lottoResultList;
전체 메서드와 변수명을 추상적인 이름으로 변경했습니다.

[2c4a95b](https://github.com/next-step/java-lotto-kakao/pull/23/commits/2c4a95b1bc3294a5ac665b950c1237a75ecb1fc2)

2024-04-04 15:44 UTC, RyooChan commented on src/main/java/model/calculator/Calculator.java
> +    public static Calculator createCalculator(List<LottoResult> lottoResultList, WinMatch winMatch) {
이전 코멘트와 연관된 내용인데요, Calculator 생성 후 유저는 이익률 / 전체 등수 현황 의 검색이 가능합니다.
그래서 아예 처음 생성될 때에 Calculator 자체가 이 상태를 보관한다면 어떤 내용을 호출해도 바로 사용이 가능할 것 같다는 생각이 들었습니다.
이렇게 하면 메서드 간 결합도가 조금 낮아질 수 있을 것 같은데, 리뷰어님의 생각이 궁금합니다.

2024-04-04 16:41 UTC, RyooChan commented on src/main/java/model/winningLottery/Lottery.java
> +    public Ranking rank(LottoNumbers lottoNumbers) {
말씀해주신 대로 Ranking 에 로직 전체 적용하였습니다~!

[88270f6](https://github.com/next-step/java-lotto-kakao/pull/23/commits/88270f64f49f39be47731f2cfd91830785d531bf)

2024-04-05 10:01 UTC, seokhong approved these changes
류찬님, 1단계 미션 코멘트 잘 반영하셨습니다. 👍 
1단계 PR 머지하겠습니다.
추가로 코멘트 남긴 내용은 다음 단계 미션 진행하실 때 참고해 보시면 좋겠습니다.
2단계 미션에서 뵙겠습니다. 🙂

2024-04-05 10:01 UTC, seokhong commented on src/main/java/model/winningLottery/Ranking.java
> +    private static boolean isRanking(Ranking ranking, int winningMatchCount, boolean isBonusMatch) {
보너스 번호 매치 여부가 2등일 때만 확인이 필요하여, 보너스 번호를 검증하는 로직이 복잡해진 것으로 보이네요.
각 등수의 당첨 여부를 enum 객체가 스스로 관리해보면 어떨까요?
enum 의 abstract method 또는 람다를 이용한 방법을 찾아보시면 좋겠습니다. 이런 내용이 정리된 [블로그](https://velog.io/@ljinsk3/Enum%EC%9C%BC%EB%A1%9C-%EB%8B%A4%ED%98%95%EC%84%B1%EC%9D%84-%EA%B5%AC%ED%98%84%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95)도 있네요!

2024-04-05 10:01 UTC, seokhong commented on src/main/java/model/random/RandomNumberGenerator.java
> +        shuffle(lottoNums);
위에 남긴 코멘트를 확인하지 못하신 것 같아서 추가로 코멘트 남깁니다. :)

`lottoNums`라는 필드를 그대로 노출하지 말고, `allBalls()`, `allLottoNumbers()` 등의 메서드로 제공해보면 어떨까요?
1. static 변수는 여러 스레드에서 동시에 접근/수정하는 경우 스레드 경합에 의한 버그가 발생할 위험이 있습니다.
2. 원본 데이터를 외부에서 접근하도록 열어 놓으면, 원본 데이터를 외부에서 임의로 변경하여 버그가 발생할 위험이 있습니다.
3. 메서드로 감싸서 제공하면, 필요에 의해 `lottoNums`의 구현이 달라지더라도 이를 사용하는 코드에는 변경이 불필요 합니다.

또한 `lottoNums`에 약어가 사용됐는데, 전체적으로 약어를 사용하는 코드를 확인해 보시면 좋겠습니다.

2024-04-05 10:01 UTC, seokhong commented on src/main/java/model/random/RandomNumberGenerator.java
> +            .limit(6)
6이라는 값은 `LottoNumbers`에서 관리해야 할 숫자로 보이기도 하는데요.
관련해서 https://github.com/next-step/java-lotto-kakao/pull/23/files#r1551299398 코멘트를 남겼네요. 확인해 보시면 좋겠습니다. :)

2024-04-05 10:01 UTC, merged