로또 1단계 미션 제출합니다
next-step/java-lotto-kakao pull request #26
Opened 2024-04-02 14:30 UTC by BuchuKim

## 신경쓴 사항
- 로또 숫자 `LottoBall`, 한 장의 로또 `Lotto`, 여러 개의 로또를 갖는 `Lottos`, 로또를 구매할 때 사용되는 `LottoMoney`와 상금을 뜻하는 `WinningMoney` 등 모든 값을 래핑했습니다.
- 컨트롤러단에서 사용자 입력값에 대한 예외처리를 `try-catch` 했습니다. 이 떄 인덴트가 2개를 넘어가지 않도록 주의했습니다.
- 몇 등 당첨인지, 즉 `Rank` enum값에 따라 결과를 출력할 때 메세지 생성의 책임을 어디서 해야할지 고민이었습니다.

2024-04-02 17:45 UTC, Rok93 requested changes
승희님 안녕하세요. 
로또 미션을 함께하게된 김경록입니다. 🙇‍♂️

1단계 구현 잘해주셨습니다. 👍👍
몇몇 코멘트 남겨두었으니 확인해서 반영 부탁드려요. 🙏
미션 진행하면서 어려운 부분이있으면 언제든지 DM 주세요. 🙂

2024-04-02 17:45 UTC, Rok93 commented on README.md
> +- [x] 사용자의 입력을 받는다.
기능 구현 목록표 꼼꼼하게 잘 작성해주셨네요. 👍💯

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/LottoGameApplication.java
> +			= new LottoGameController(lottoGameView, lottoGenerator);
줄 바꿈까지는 필요없는 길이인 것 같아요. 🙂

```suggestion
		LottoGameController lottoGameController = new LottoGameController(lottoGameView, lottoGenerator);
```

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/controller/LottoGameController.java
> +		return getLottoMoney();
catch 문 안에서 다시 `getLottoMoney` 객체를 호출하도록 변경해주면 될 것 같아요. 😃

```suggestion
                     return getLottoMoney();
		}
```

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/controller/LottoGameController.java
> +	}
메서드를 호출되는 순서대로 위치시키면 코드를 파악하기가 조금 더 수월할 것 같아요. 😉
```suggestion
        private Lotto getWinningLottoNumbers() {
		try {
			List<LottoBall> winningLottos = lottoGameView.getWinningLottoNumbers();
			return new Lotto(winningLottos);
		} catch (NumberFormatException e) {
			System.out.println("[ERROR] \", \"로 구분되는 숫자를 입력해주세요!");
			return getWinningLottoNumbers();
		} catch (IllegalArgumentException e) {
			System.out.println("[ERROR] " + e.getMessage());
			return getWinningLottoNumbers();
		}
	}
	
	private WinningLotto getWinningLotto(Lotto winningLottoNumbers) {
		try {
			LottoBall bonusNumber = new LottoBall(lottoGameView.getBonusNumber());
			return new WinningLotto(winningLottoNumbers, bonusNumber);
		} catch (IllegalArgumentException e) {
			System.out.println("[ERROR] " + e.getMessage());
			return getWinningLotto(winningLottoNumbers);
		}
	}
```

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/EarningRate.java
> +	}
`winningResult` 객체에게  수익률을 계산하는 책임을 위임해보면 어떨까요? 😃

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/Lotto.java
> +	private final List<LottoBall> lottoNumbers;
인스턴스 변수 명은 `lottoNumber`인데  래퍼 클래스는 `LottoBall` 이군요? 🤔
개인적으로는 `LottoNumber`가 조금 더 직관적인 것 같아요. 🙂

추후 LottoBall 타입을 가진 lottoNumber이런식으로 소통해야할텐데 불필요한 소통비용이 들어갈 수 있을 것 같아서 조금 더 직관적인 네이밍을 가지면 좋겠다는 생각이 들었어요.😆

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/Lotto.java
> +		return lottoNumbers;
외부에서 lottoNumbers를 함부로 수정할 수 없도록 [방어적 복사](https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable/)를 해보면 어떨까요? 🙂

추가적으로 이런 getter, setter와 같은 자바의 관용적인 메서드들은 최하단에 위치시켜주시고 다른 객체와 협력하기위한 public 메서드들은 상단으로 올려주세요. 🙏
그러면 조금 코드를 파악하기가 수월해질 것 같아요. 🙂

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/LottoBall.java
> +	private final int lottoBall;
원시값을 포장하는 케이스는 인스턴스 변수의 네이밍이 조금 애매할 때가 있어요. 😃
전 개인적으로 `value`와 같은 네이밍을 추천하는 편이에요. 😉

```suggestion
	private final int value;
```

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/LottoBall.java
> +	}
이런 메서드 시그니처는  Lotto의 생성자 혹은 Lotto의 정적 팩토리 메서드에 들어가는게 조금 더 좋을 것 같아요. 🤔

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/LottoBall.java
> +		if (lottoBall < 1 || lottoBall > 45) {
`1`, `45` 같은 숫자는 [매직 넘버](https://javabom.tistory.com/28)로 보이네요.  🙂

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/LottoBall.java
> +public class LottoBall implements Comparable<LottoBall> {
로또 숫자는 1 ~ 45 까지의 숫자밖에 없기 때문에 LottoBall 객체 또한 1 ~ 45 까지의 LottoBall 객체만 사용할거에요. 
이런 `LottoBall` 객체를 미리 [캐싱](https://tecoble.techcourse.co.kr/post/2020-06-24-caching-instance/)해두고 재사용해보면 어떨까요? 🙌

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/LottoBall.java
> +		return this.lottoBall - lottoBall.getLottoBall();
같은 클래스끼리는 인스턴스 변수에 직접 접근이 가능하니 아래와 같이 변경해볼 수 있겠네요. 😉
```suggestion
		return this.lottoBall - lottoBall.lottoBall;
```

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/RandomLottoGenerator.java
> +		return new Lottos(lottos);
아래와 같은 방식으로 변경해볼 수 있겠네요. 😉
```suggestion
		return Stream.generate(this::generateLotto)
			.limit(lottoCount)
			.collect(Collectors.collectingAndThen(Collectors.toList(), Lottos::new));
```

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/WinningLotto.java
> +		return Rank.MATCH_FIVE;
`findByMatchNumberCount` 정적 팩토리 내부에서 전달받은 보너스볼 일치 여부 정보를 가지고 적절한 `Rank` 객체를 반환해주는 것이 더 깔끔할 것 같아요. 🙂
```suggestion
                boolean hasBonusNumber = hasBonusNumber(lotto);
		return Rank.findByMatchNumberCount(matchNumberCount, hasBonusNumber);
		
```

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/WinningLotto.java
> +		return (int) targetLottoNumbers.stream().filter(winnigLotto::contains).count();
아래와 같이 lotto 객체에게 [메시지를 보내](https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/)보면 어떨까요? 
```suggestion
		return winnigLotto.countSameNumber(lotto);
```

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/WinningMoney.java
> +	public static final long MATCH_SIX = 2_000_000_000;
이 값들은 별도로 상수로 둘 필요 없이 Rank 객체의 각 enum 요소들을 생성할 때, 직접 하드코딩해도 충분할 것 같아요. 😃

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/WinningResult.java
> +		lottos.getLottos().forEach(lotto -> result.add(winningLotto.getRank(lotto)));
객체를 생성하는 시점에 책임을 수행하려하지말고 객체를 생성하는 시점(= 생성자)에는 객체가 책임을 수행하기위해서 인스턴스를 완전히 할당(= 책임을 곧바로 수정할 수 있는 상태로 만드는 과정) 

협력하는 객체가 (public 메서드로) WinningResult 객체에게 메시지를 보내면 우승 상금을 계산하고 그 반환 값으로 WinningMoney를 반환해주면 조금 더 객체지향적인 코드가 될 것 같아요. 😁

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/Lotto.java
> +	public boolean contains(LottoBall lottoNumber) {
아래의 케이스에 대해서 테스트 코드 작성 부탁드려요. 🙏

* contains
* Lotto 객체 생성 테스트 (특히 예외 케이스!)

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/WinningLotto.java
> +	}
사용하는 위치가 테스트 코드쪽 밖에 없는 것 같은데 테스트만을 위한 메서드라면 제거해도 될 것 같아요.

2024-04-02 17:45 UTC, Rok93 commented on src/main/java/domain/Rank.java
> +	public static Rank findByMatchNumberCount(int matchNumberCount) {
이 정적 팩토리 메서드에대한 테스트도 작성해주세요. 🙏

2024-04-02 23:29 UTC, BuchuKim commented on src/main/java/domain/EarningRate.java
> +	}
`WinnigResult`는 당첨 결과(몇 등이 몇 개 당첨됐는지, 당첨금은 얼마인지)만을 담고있습니다. 플레이어의 복권 구매 개수와 그리고 그 수익률은 `WinningResult`에 담기에 바람직하지 않다고 생각했어요!

2024-04-02 23:31 UTC, BuchuKim commented on src/main/java/domain/Lotto.java
> +	private final List<LottoBall> lottoNumbers;
`LottoBall` -> `LottoNumber`로 바꾸어 조금 더 직관적인 이름을 갖도록 했습니다.

2024-04-02 23:32 UTC, BuchuKim commented on src/main/java/domain/Lotto.java
> +		return lottoNumbers;
```java
return Collections.unmodifiableList(lottoNumbers);
```
사용하고 하단에 메소드 위치 옮겼습니다.

2024-04-02 23:37 UTC, BuchuKim commented on src/main/java/domain/LottoBall.java
> +	}
`Lotto.from`으로 옮겼습니다~~!

2024-04-03 01:00 UTC, BuchuKim commented on src/main/java/domain/LottoBall.java
> +public class LottoBall implements Comparable<LottoBall> {
로또를 생성하는 `RandomNumberGenerator`에서 1부터 45까지의 값을 갖는 `List<LottoBall>`(현재는 `LottoNumber`로 수정됨)을 스태틱 필드로 갖고있도록 구성했습니다~

2024-04-03 01:17 UTC, BuchuKim commented on src/main/java/domain/WinningLotto.java
> +		return (int) targetLottoNumbers.stream().filter(winnigLotto::contains).count();
모든 로또에게 필요하다기보단 `WinningLotto`에서만 필요하다 생각했습니다. 근데 `Lotto`에서 해당 역할을 수행할 수 있도록 하면 아예 지금 이 메소드는 필요 없겠네요! 삭제하고 `getRank()`에 옮겼습니다.

2024-04-03 01:18 UTC, BuchuKim commented on src/main/java/domain/WinningMoney.java
> +	public static final long MATCH_SIX = 2_000_000_000;
`Rank`에서 요소로 당첨 금액 필드로 `WinningMoney winningMoney`를 갖도록 구성하고 싶었습니다. 그래야`Rank`가 당첨 금액을 갖고있다는 의미를 더 확실히 할 수 있고 당첨금액을 래핑한 의미도 살기 때문에 😅

2024-04-03 01:23 UTC, BuchuKim commented on src/main/java/domain/WinningResult.java
> +		lottos.getLottos().forEach(lotto -> result.add(winningLotto.getRank(lotto)));
그러면 `WinningResult`에서는 당첨 정보를 갖고있는 `winningLotto`, 그리고 사용자가 구매한 `lottos` 정보를 필드로 전부 가지고있어야 한다는 의미일까요? 그리고 `calculate()` 혹은 `getResult()`같은걸 호출할 때 위 코드의 로직을 수행하라는 말씀이시죠?

근데 개인적으로는 단계를 더 늘린다는 느낌을 피할 수 없는데..(`of()`에 전달되는 값은 생성시점 이외에 쓰이지 않기 때문) 이게 더 객체지향적인 이유가 뭘까요?

2024-04-03 01:27 UTC, BuchuKim commented on src/main/java/domain/Lotto.java
> +	public boolean contains(LottoBall lottoNumber) {
객체 생성 테스트는 `LottoNumberTest`와 현재 `LottoTest`에 이미 작성되어 있고,
contains는 추가했습니다~

2024-04-03 01:31 UTC, BuchuKim commented on src/main/java/domain/WinningLotto.java
> +	}
제거했습니다. 그리고 기존의 `WinningLottoTest`에서 여러개 있던 테스트를 제거하고 `rank`와 `winningMoney`를 한번에 확인할 수 있도록 고쳤어요~

2024-04-03 01:46 UTC, BuchuKim commented on src/main/java/domain/EarningRate.java
> +	}
`WinningResult#calculateEarningRate()` 메소드 추가했습니다~~

2024-04-03 05:55 UTC, BuchuKim commented on src/main/java/domain/LottoBall.java
> +	}
`Lotto#from`을 고민하다가, 아예 `LottoGenerater`에서 `LottoNumber`로 매핑된 리스트를 반환하도록 해서, 현재 `LottoBall#toLotto` 메소드를 없앴습니다!

2024-04-03 12:29 UTC, Rok93 approved these changes
승희님 피드백 반영 잘해주셨네요. 👍

이정도면 1단계는 충분한 것 같아서 이만 머지하도록하게습니다. 🙂
질문 남겨주신부분은 제 생각을 남겨두었으니 확인 부탁드릴게요. 🙏

다음 단계에서 뵐게요.

2024-04-03 12:29 UTC, Rok93 commented on src/main/java/domain/WinningResult.java
> +		lottos.getLottos().forEach(lotto -> result.add(winningLotto.getRank(lotto)));
> 근데 개인적으로는 단계를 더 늘리고 상태값을 필요 이상으로 늘린다는 느낌을 피할 수 없는데..(of()에 전달되는 값은 계산시점 이외에 쓰이지 않기 때문) 이게 더 객체지향적인 이유가 뭘까요?


객체는 `하나의 책임`을 가지고 `다른 객체와 협력`하여  비즈니스를 수행하는 것이 객체지향 프로그래밍이기 때문이죠. 😃
이 과정에서 객체가 불필요하게 많다고 느낄 수도 있지만 이런 부분이 트레이드 오프라고 볼 수 있을 것 같아요. 🙂

역할과 책임이 명확하면 이후의 변경에 유연해지기 때문에 유지보수성이 높아지는 장점이 있어요. (응집도가 높아지고 결합도는 낮아질거에요. 🙂)

2024-04-03 12:29 UTC, Rok93 commented on src/main/java/domain/WinningMoney.java
> +	public static final long MATCH_SIX = 2_000_000_000;
그렇다면 `Rank`의 모든 요소를 `WinningMoney`가 알아야하겠네요? 🤔

WinningMoney와 Rank가 강한 의존성을 가지게 될 것으로 보입니다. 
그렇다면 둘 중 하나에 변경이 발생한다면 이 변경은 의존하는 다른 클래스에도 영향을 미칠 수 있어요. 
물론 지금처럼 규모가 작은 서비스라면 이 변경을 금방 감지할 수 있겠지만 규모가 큰 서비스라면 어떻게될까요? 
아마도 변경에의한 사이드 이펙트를 감지하기가 어려울거에요. 🥲
결국 이런 사이드 이펙트는 예상치 못한 장애로 이어질 확률이 높아지게될거에요. 

그렇기 떄문에 가급적 불필요한 의존성은 제거하는 것이 좋다고 생각됩니다. 

간단한 예로 아래와 같이 enum 요소를 등수로 변경해보면 어떨까요? 🙂

MATCH_SIX -> 1등
MATCH_FIVE_WITH_BONUS ->  2등
MATCH_FIVE ->  3등
MATCH_FOUR ->  4등
...

2024-04-03 12:29 UTC, Rok93 commented on src/main/java/domain/Lotto.java
> +		return (int) lotto.getLottoNumbers().stream().filter(this::contains).count();
한 줄에 하나의 함수만 호출하도록 아래와 같이 변경하면 조금 더 가독성이 좋아질 것 같네요. 🙂

```suggestion
		return (int) lotto.getLottoNumbers().stream()
		    .filter(this::contains)
		    .count();
```

2024-04-03 12:29 UTC, Rok93 commented on src/main/java/domain/WinningMoney.java
> +	public void addWinningMoney(WinningMoney winningMoney) {
메서드 네이밍을 `add` 로 변경해도 괜찮지 않을까 싶어요. 🤔

외부에서 호출하는 형태를 보면 아래와 같을 것 같은데 
`winningMoney.add(otherWinningMoney)` 

add 정도의 네이밍도 충분히 의도를 드러낼 수 있을 것 같아요. 🙂

2024-04-03 12:29 UTC, merged

2024-04-04 05:22 UTC, BuchuKim commented on src/main/java/domain/WinningMoney.java
> +	public void addWinningMoney(WinningMoney winningMoney) {
어떤 의미로 말씀하신지 알겠습니다! 인자에 의미가 있는 것은 간단한 메소드명을 사용하도록 해볼게요^^

2024-04-04 05:43 UTC, BuchuKim commented on src/main/java/domain/WinningMoney.java
> +	public static final long MATCH_SIX = 2_000_000_000;
아,, enum의 이름으로 말씀해주시니까 와닿네요. 당첨금이 Rank를 알게 된다는게 그 의미군요!
하드코딩 하는대신 각 가격을 나타내는 숫자 상수를 보관하는 인터페이스 추가했고, enum 이름도 수정했습니다~~!!~