로또 2단계 미션 제출합니다.
next-step/java-lotto-kakao pull request #33
Opened 2024-04-04 02:58 UTC by kjk7212

기존에 객체를 많이 만들어두고 책임을 열심히 나누어 두었더니
생각보다 빠르게 객체들의 기능 조합으로 구현 할 수 있었습니다.

2024-04-05 11:56 UTC, shared-moon requested changes
성국님 안녕하세요!
2단계 미션 잘 진행 해 주셨네요 :)
수동 추가하는건 큰 어려움 없이 잘 마무리 해 주신 것 같아요.
하지만 한번 생각해봤으면 하는 부분이 있어서, 피드백 확인 후 리뷰 재요청 부탁드려요
고생 많으셨습니다 ~

2024-04-05 11:56 UTC, shared-moon commented on src/main/java/controller/LottoGame.java
> +	private void settingManualLotto(Money money) {
setter를 습관적으로 쓰시는 것 같아요.
멤버변수를 변경하는게 아니라 가급적 메서드의 리턴으로 받아서 활용하는 걸 의식적으로 연습해보시면 어떨까요?
기본적으로 setter는 상태를 가지게 해서 멀티스레드 환경에서 문제를 일으킬 소지도 많고 재사용도 어렵게 만들어서 좋은 패턴이 아니라고 생각합니다 :)

2024-04-05 11:56 UTC, shared-moon commented on src/main/java/model/Lotto.java
> +		return lottoNumbers.stream()
LottoNumber에 equals & hashcode를 구현하면 contains로 찾아볼 수 있지 않을까요 ?

2024-04-05 11:56 UTC, shared-moon commented on src/main/java/model/LottoResult.java
> +		Arrays.stream(LottoRankInfo.values())
맞는 LottoRankInfo를 찾는 부분은 LottoRankInfo의 역할인게 더 어울리지 않을까요 ?

2024-04-06 10:58 UTC, kjk7212 commented on src/main/java/model/LottoResult.java
> +		Arrays.stream(LottoRankInfo.values())
해당 enum 파일에 static 함수를 추가해서 역할을 넘겼습니다!

2024-04-06 10:59 UTC, kjk7212 commented on src/main/java/model/Lotto.java
> +		return lottoNumbers.stream()
java가 익숙하지 않아서 equals를 오버라이드 하면 contains로 되는지 몰랐습니다....
바로 반영하도록 하겠습니다!

2024-04-06 10:59 UTC, kjk7212 commented on src/main/java/controller/LottoGame.java
> +	private void settingManualLotto(Money money) {
값들을 모아서 리스트를 만들고 해당 리스트를 통해서 생성자로 Lottos를 생성하는 방식으로 변경 했습니다!

2024-04-07 03:48 UTC, shared-moon requested changes
성국님 안녕하세요!
피드백 반영 잘 해 주셨네요 :)
기능구현 다 잘 해 주셨는데, 추가로 조금만 더 살펴보면 좋을 것 같아요
피드백 확인 후 다시 리뷰요청 부탁드려요 ~
고생 많으셨습니다!

2024-04-07 03:48 UTC, shared-moon commented on src/main/java/constant/LottoRank.java
> +			.sorted(Comparator.comparingInt(LottoRank::getPrize).reversed())
정렬이 꼭 필요할까요 ? 2등 때문에 쓰신 것 같은데, 만약에 2등과 1등 혹은 2등과 3등 사이 다른 무언가가 생긴다면 생각한대로 동작을 안 할 수도 있을 것 같아요. 그리고 잘 생각해보면 2등은 다른 등수와는 검사 로직이 다른 녀석이라고 판단할 수도 있을 것 같아요.

2등 검사 로직(보너스 번호가 필요한 로직)을 그냥 아예 빼고, 그게 아닌 경우에만 공통된 로직을 타도록 해보는 건 어떨까요 ?

2024-04-07 03:48 UTC, shared-moon commented on src/main/java/controller/LottoGame.java
> +	private void settingLottos(Money money) {
setter를 이용하시는게 여전히 남아있는 것 같아요

settingLottos가 아니라 createLottos 처럼 만들고 Lottos를 리턴하는 메서드로 만들면 어떨까요 ? 굳이 상태로 관리 될 이유가 없어보여요

2024-04-07 03:48 UTC, shared-moon commented on src/main/java/controller/LottoGame.java
> +		lottos = new Lottos(Stream.concat(manualLottos.stream(), autoLottos.stream()).collect(Collectors.toList()));
addAll을 이용해도 되지 않을까요 ?

2024-04-07 03:48 UTC, shared-moon commented on src/main/java/controller/LottoGame.java
> +		return new Lotto(parseNumbersWithComma(lottoNumbers).stream()
요 밑에 부분에 대한 얘긴데, LottoNumber는 1~45까지만 가지고 있어서 사실 계속 생성 될 필요가 없는 객체인데, 현재는 new로 항상 새로운 객체가 만들어지고 있어요. 이걸 개선해 볼 방법은 없을까요 ?

2024-04-07 03:48 UTC, shared-moon commented on src/main/java/model/LottoResult.java
> +			.collect(Collectors.toMap(lottoRank -> lottoRank, lottoRank -> 0));
자기 자신을 리턴해줄땐 `Functions.identity()` 를 사용할 수도 있어요 ~

2024-04-07 03:48 UTC, shared-moon commented on src/main/java/model/LottoResult.java
> +		result.put(lottoRank, result.getOrDefault(lottoRank, 0) + 1);
put 대신에 compute를 사용해보는 건 어떨까요 ?

2024-04-07 12:10 UTC, kjk7212 commented on src/main/java/constant/LottoRank.java
> +			.sorted(Comparator.comparingInt(LottoRank::getPrize).reversed())
확실히 이후 등수 체계에 변화가 생기면 제대로 작동하지 않을 것 같아서,
이후의 변화에도 잘 적응 할 수 있게 끔 일단 맞은 숫자를 체크해서 등수를 내고
보너스가 true일때는 보너스로 상금이 증가 할 때만 등수가 변할 수 있게 로직을 개선 했습니다!

2024-04-07 12:11 UTC, kjk7212 commented on src/main/java/controller/LottoGame.java
> +	private void settingLottos(Money money) {
변수를 제거하고 전부 반환 값으로 처리하게 변경 했습니다!

2024-04-07 12:13 UTC, kjk7212 commented on src/main/java/controller/LottoGame.java
> +		return new Lotto(parseNumbersWithComma(lottoNumbers).stream()
기존의 LottoMachine에서 사용하던 1~45의 LottoNumber의 static 리스트를 상수 파일로 옮기고
메모리에 이미 있는 객체를 반환하게 개선 했습니다!

2024-04-07 13:07 UTC, shared-moon approved these changes
성국님 안녕하세요!
피드백 반영 잘 해 주셨네요 :)
코멘트를 좀 남겨 두었는데, 다음 미션 진행 전 확인 부탁드립니다!
고생 많으셨어요!

2024-04-07 13:07 UTC, shared-moon commented on src/main/java/model/LottoNumber.java
> +		return lottoNumberPool.stream()
순서가 정해져있는 숫자값이라 순회하기보단 배열처럼 접근하는게 어떨까 싶어요 ~ `Integer.valueOf` 메서드 참고해보시면 좋을 것 같습니다!

2024-04-07 13:07 UTC, shared-moon commented on src/main/java/constant/LottoConstants.java
> +	public static final List<LottoNumber> lottoNumberPool = IntStream.rangeClosed(NUMBER_LOWER_BOUND, NUMBER_UPPER_BOUND)
static 변수는 보통 UPPER CAMEL CASE를 사용합니다! `LOTTO_NUMBER_POOL` 요렇게요~

2024-04-07 13:07 UTC, shared-moon commented on src/main/java/constant/LottoRank.java
> +			.filter(rank -> (rank.getBonus() && rank.getPrize() > lottoRank.getPrize() && rank.getMatchCount() == lottoRank.getMatchCount()))
prize는 왜 보는걸까요 ?

그리고 보통 스트림연산에서 filter 조건이 여러개인 경우는 filter를 여러번 선언해주시는게 좋아요 ~ 이렇게 조건이 다 드러나게 보이면 선언형의 장점이 조금 퇴색되는 면이 있어요!

2024-04-07 13:07 UTC, merged