로또 2단계 미션 제출합니다.
next-step/java-lotto-kakao pull request #35
Opened 2024-04-04 06:29 UTC by skh1225

첫번째 PR에서 리뷰 해주신 부분 수정하였습니다.
* 코드 가독성 및 중복 제거
    * 커밋 : https://github.com/skh1225/java-lotto-kakao/commit/db32ccbf2b9ef182074a657b438dacd379ac56bb
    * 코멘트 : https://github.com/next-step/java-lotto-kakao/pull/14#discussion_r1549683217, https://github.com/next-step/java-lotto-kakao/pull/14#discussion_r1549782272, https://github.com/next-step/java-lotto-kakao/pull/14#discussion_r1549796439, https://github.com/next-step/java-lotto-kakao/pull/14#discussion_r1549799470
* LottoNumbers 캐싱 관련
    * 커밋 : https://github.com/skh1225/java-lotto-kakao/commit/2a1fc272d721c2d261e88bf949962a77f32f4fba
    * 코멘트 : https://github.com/next-step/java-lotto-kakao/pull/14#discussion_r1549782441, https://github.com/next-step/java-lotto-kakao/pull/14#discussion_r1549774258
* LottoTicket 랜덤 생성 로직 LottoTicketGenerator로 이관
    * 커밋 : https://github.com/skh1225/java-lotto-kakao/commit/d47bee3d72493803e54ca19be272be831d4807f5
    * 코멘트 : https://github.com/next-step/java-lotto-kakao/pull/14#discussion_r1549787492
* LottoTicket에 존재했던 view 로직을 LottoView로 이관
    * 커밋 : https://github.com/skh1225/java-lotto-kakao/commit/40fb98102e7d3506ea65fcc9a7e6f74a5c28d4dd
    * 코멘트 : https://github.com/next-step/java-lotto-kakao/pull/14#discussion_r1549791536

Step2 미션인 수동으로 로또 번호를 받는 로직을 추가하였습니다.
* 커밋 : https://github.com/skh1225/java-lotto-kakao/commit/69fb1338fd7fb65c429b474b34bc2bdd9698c72c

2024-04-04 16:17 UTC, Rok93 requested changes
경환님 2단계 빠르게 잘 구현해주셨어요. 👍💯
전체적으로 깔끔해서 크게 피드백드릴 부분이 없었어요. 👏👏 
몇몇 코멘트 남겨두었는데, 확인해서 수정부탁드릴게요. 🙏

2024-04-04 16:17 UTC, Rok93 commented on src/main/java/controller/LottoController.java
> +
사용하지 않는 import문은 제거해주세요. 🙏
단축키를 이용해서 이런 불필요한 import문을 제거할 수 있어요. (맥: `⌃ + ⌥ + O`, 윈도우: ` Ctrl + Alt + O`)

2024-04-04 16:17 UTC, Rok93 commented on src/main/java/controller/LottoController.java
> +		cash.purchase(LottoTicket.PRICE, countOfManualTickets);
아래의 `cash.getTicketCount();` 의 로직을 봤을 때는 이미 `LottoTicket.PRICE`에 의존하고있는 것 같은데 굳이 여기서는 외부에서 주입받을 필요가 있을까요? 🤔

`cash.purchaseLottoTickets(countOfManualTickets);`와 같이 의미만  조금 수정하고 내부에서 직접 의존하는게 조금 더 나아보여요. 🙂

2024-04-04 16:17 UTC, Rok93 commented on src/main/java/controller/LottoController.java
> +		lottoTickets.addRandomLottoTicket(countOfRandomTickets);
기존의 lottoTickets에 새로운 lottoTickets들을 add하는 것 보다는 
두 lottoTickets를 합쳐서 새로운 LottoTickets으로 만드는 방식으로 변경해보면 어떨까요? 😃


```suggestion
		LottoTickets totalLottoTicket = lottoTickets.plus(countOfRandomTickets);
		
		...
		return totalLottoTicket;
```

2024-04-04 16:17 UTC, Rok93 commented on src/main/java/controller/LottoController.java
> +		return lottoGame.calculateResult();
lottoGame의 `calculateResult` 메서드 로직  (PR에는 해당 코드가 안나와서 여기에 코멘트 남길게요 👀)

아래의 로직은 `LottoTickets`의 [객체에게 메시지를 보내](https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/)보면 어떨까요? 
```java
                LottoGameResult result = new LottoGameResult();
		for (LottoTicket lottoTicket : lottoTickets.getLottoTickets()) {
			LottoWinningRank lottoWinningRank = lottoWinningNumbers.calculateResult(lottoTicket);
			result.add(lottoWinningRank);
		}
		return result;
```

추가적으로 LottoGameResult 객체를 생성하는 시점에 이미 완성된 (= 모든 요소가 추가된) List<LottoTicket>을 생성해서 생성자 파라미터로 전달해주면 어떨까요? 😃

2024-04-04 16:17 UTC, Rok93 commented on src/main/java/domain/LottoNumber.java
> +	private static final List<LottoNumber> LottoNumbers;
기존의 상수명에서 네이밍을 변경하면서 상수 네이밍 규칙을 위배되는 네이밍으로 바꼈네요. 🥲
상수 네이밍 규칙에 맞춰서 명명 부탁드려요. 🙏

2024-04-04 16:17 UTC, Rok93 commented on src/main/java/domain/LottoTickets.java
> +	public void addRandomLottoTicket(int count) {
`LottoTickets`의 입장에서는 새롭게 추가되는 로또티켓이 랜덤인지 수동인지가 관심사가 아닐 것 같아요. 😃

`LottoGenerator` 객체에게 생성할 로또 갯수를 입력받으면 해당 갯수만큼의 (랜덤한) LottoTickets 을 생성해주는 역할을 위임해주면 어떨까요? 🙂

2024-04-04 16:17 UTC, Rok93 commented on src/main/java/domain/WinningLottoTicket.java
>  	public LottoWinningRank calculateResult(LottoTicket lottoTicket) {
`calculateResult`에 대한 테스트 코드도 작성해주세요. 🙏

추가적으로 네이밍도 반환하는 타입명과 결을 맞춰서 `calculateWinningRank` 와 같이 변경해보는건 어떨까요? 🤔

2024-04-06 13:17 UTC, skh1225 commented on src/main/java/controller/LottoController.java
> +		cash.purchase(LottoTicket.PRICE, countOfManualTickets);
반영했습니다. https://github.com/next-step/java-lotto-kakao/pull/35/commits/dea9ba0f3d69defde5d5eda55e7984f0f2634026

2024-04-06 13:23 UTC, skh1225 commented on src/main/java/controller/LottoController.java
> +		lottoTickets.addRandomLottoTicket(countOfRandomTickets);
LottoTickets를 불변객체로 만들라는 말씀이시군요?
반영했습니다. https://github.com/next-step/java-lotto-kakao/pull/35/commits/113c2bf2fe873db2007dcf275c5f59d92951a4d5

2024-04-06 13:27 UTC, skh1225 commented on src/main/java/controller/LottoController.java
> +		return lottoGame.calculateResult();
링크 감사합니다 :) 객체스러움에대해 더 생각해볼 수 있었네요 https://github.com/next-step/java-lotto-kakao/pull/35/commits/4c3bf71aefdb18e4c4646e542dbabcbb8d65b7c2

2024-04-06 13:28 UTC, skh1225 commented on src/main/java/controller/LottoController.java
> +
단축키 유용하네요 ㅎㅎ https://github.com/next-step/java-lotto-kakao/pull/35/commits/e15df4baae97f2b9e368a967e9cddf2cb2dd8016

2024-04-06 13:28 UTC, skh1225 commented on src/main/java/domain/LottoNumber.java
> +	private static final List<LottoNumber> LottoNumbers;
반영했습니다. https://github.com/next-step/java-lotto-kakao/pull/35/commits/01d20260408a9cb8f6119c876c2db98938fd1600

2024-04-06 13:34 UTC, skh1225 commented on src/main/java/domain/LottoTickets.java
> +	public void addRandomLottoTicket(int count) {
반영하였습니다.
네이밍 수정 (https://github.com/next-step/java-lotto-kakao/pull/35/commits/01d20260408a9cb8f6119c876c2db98938fd1600), LottoGenerator에 기능 구현(https://github.com/next-step/java-lotto-kakao/pull/35/commits/113c2bf2fe873db2007dcf275c5f59d92951a4d5)

2024-04-06 13:35 UTC, skh1225 commented on src/main/java/domain/WinningLottoTicket.java
>  	public LottoWinningRank calculateResult(LottoTicket lottoTicket) {
반영하였습니다. https://github.com/next-step/java-lotto-kakao/pull/35/commits/36c7d89d0eff9ef27771da8e423127ac8c649a68

2024-04-07 08:58 UTC, Rok93 requested changes
경환님 피드백 반영 잘해주셨습니다. 👍👍
조금 더 얘기해보면 좋을 부분이있어 코멘트 남겨두었습니다. 🙂
코멘트 확인해서 반영 부탁드려요. 🙏

2024-04-07 08:58 UTC, Rok93 commented on src/main/java/controller/LottoController.java
> +		LottoTickets totalLottoTickets = lottoTickets.plus(LottoTicketGenerator.generateRandomLottoTickets(countOfRandomTickets));
사소하지만 `manualLottoTickets`, `autoLottoTickets`으로 변수명을 두고 manualLottoTickets.plus(auttoLottoTickets) 와 같이 코드를 표현해주면   로또 티켓들은  수동로또 티켓들과 자동로또 티켓들이 같이 있구나? 라고 이해하기 쉬울 것 같아요. 😃

```suggestion
                 LottoTickets autoLottoTickets = LottoTicketGenerator.generateRandomLottoTickets(countOfRandomTickets);
		LottoTickets totalLottoTickets = manualLottoTickets.plus(autoLottoTickets);
```

2024-04-07 08:58 UTC, Rok93 commented on src/main/java/domain/LottoNumber.java
> +			return LOTTO_NUMBERS.get(value-1);
코드 정렬이 안된 것 같아요. 👀
전체적으로 코드 자동 정렬을 진행해주세요. 🙏

상위 패키지를 클릭한 뒤, 자동정렬 단축키를 누르면 아래와 같은 창이 뜨는데 이 방식으로 전체 코드에 대해서 코드 정렬을 진행할 수 있어요. 🙂 
<img width="1157" alt="image" src="https://github.com/next-step/java-lotto-kakao/assets/47850258/dcc02554-488a-41da-83cd-c269e242b802">

2024-04-07 08:58 UTC, Rok93 commented on src/main/java/domain/LottoTicketGenerator.java
> +		return new LottoTickets(lottoTickets);
아래와 같이 변경해볼 수 있을 것 같아요. 😉

```suggestion
		return Stream.generate(LottoTicketGenerator::generateRandomLottoTicket)
			.limit(countOfTickets)
			.collect(Collectors.collectingAndThen(Collectors.toList(), LottoTickets::new));
```

2024-04-07 08:58 UTC, Rok93 commented on src/main/java/domain/LottoTickets.java
> +		this.lottoTickets = lottoTickets;
일급 컬렉션 객체를 생성할 때도 [방어적 복사](https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable/)를 해보면 어떨까요? 🙂

2024-04-07 08:58 UTC, Rok93 commented on src/main/java/domain/LottoWinningRank.java
>  		if (hasBonusNumber && matchCount == 5) {
이 `5`가 어떤 값을 의미하는건지 드러내면 좋을 것 같아요. 
`SECOND_PRIZE`의 matchCount라고 드러낼 수 있겠네요. 🙂

2024-04-07 08:58 UTC, Rok93 commented on src/main/java/domain/WinningLottoTicket.java
> +	public List<LottoWinningRank> calculateWinningRanksOfTickets(LottoTickets lottoTickets) {
LottoGameResult 클래스에서 아래와 같이 `LottoGameResult` 객체를 생성하고있는데요 👀

```java
        public LottoGameResult calculateGameResult() {
		return LottoGameResult.of(winningLottoTicket.calculateWinningRanksOfTickets(this.lottoTickets));
	}
```

 `calculateWinningRankOfTicket` 메서드에서 `LottoGameResult` 객체를 만들어서 반환할 수 있을 것 같아요. 🙂

2024-04-07 08:58 UTC, Rok93 commented on src/main/java/ui/LottoView.java
> +	public static int getCountOfManualTickets() {
입력을 받아오는 View 컴포넌트 기능들이 도메인 Model에 의존하고있는  것처럼 보여요.
웹 프론트 혹은 모바일 앱으로부터  json 요청을 받는 상황을 떠올리면서 View에 Model 의존성을 제거해보면 좋을 것 같아요. 🙂

2024-04-07 14:22 UTC, skh1225 commented on src/main/java/domain/WinningLottoTicket.java
> +	public List<LottoWinningRank> calculateWinningRanksOfTickets(LottoTickets lottoTickets) {
LottoGameResult를 생성하는 책임은 LottoGame에게 있고 WinningLottoTicket에는 입력받은 LottoTickets에 대해 LottoWinningRank를 계산하여 반환하는 책임이 있다고 생각하는데 어떻게 생각하시나요? 👀

2024-04-07 14:40 UTC, skh1225 commented on src/main/java/controller/LottoController.java
> +		LottoTickets totalLottoTickets = lottoTickets.plus(LottoTicketGenerator.generateRandomLottoTickets(countOfRandomTickets));
반영했습니다. https://github.com/next-step/java-lotto-kakao/pull/35/commits/de7632de4e72c03af5ab1948a343c3470981e773

2024-04-07 14:41 UTC, skh1225 commented on src/main/java/domain/LottoNumber.java
> +			return LOTTO_NUMBERS.get(value-1);
이런 유용한 기능이 있다니.. 감사합니다 ! 👍  https://github.com/next-step/java-lotto-kakao/pull/35/commits/dfb38a990a997f2665e9728564ee2ad9d52c3dde

2024-04-07 14:42 UTC, skh1225 commented on src/main/java/domain/LottoTicketGenerator.java
> +		return new LottoTickets(lottoTickets);
반영했습니다. https://github.com/next-step/java-lotto-kakao/pull/35/commits/cacfd8dc4fc7ff246f362242b6b6a35bcb5a2b2a

2024-04-07 14:44 UTC, skh1225 commented on src/main/java/domain/LottoTickets.java
> +		this.lottoTickets = lottoTickets;
방어적 복사 ,unmodifiableList 에대해 배울 수 있었네요~ 감사합니다 👍  https://github.com/next-step/java-lotto-kakao/pull/35/commits/d22be489293f301032ca74535610adebd5fa46ac

2024-04-07 14:44 UTC, skh1225 commented on src/main/java/domain/LottoWinningRank.java
>  		if (hasBonusNumber && matchCount == 5) {
반영했습니다. https://github.com/next-step/java-lotto-kakao/pull/35/commits/93f9d914667309bedd2d50fd54bdf9742cb63e73

2024-04-07 14:49 UTC, skh1225 commented on src/main/java/ui/LottoView.java
> +	public static int getCountOfManualTickets() {
이 부분에 대해 잘 이해가 안되는데요.

`getCountOfManualTickets` 를 `getCountOfTickets` 와 같이 동작하도록 바꾸라는 의미일까요?

조금 더 설명 부탁드립니다! 🙏

2024-04-07 16:32 UTC, Rok93 commented on src/main/java/ui/LottoView.java
> +	public static int getCountOfManualTickets() {
에구... 제가 다른 위치에 코멘트를 남겨두었네요. 😅
혼동을드려 죄송해요. 🙏

`getManualLottoTickets` 메서드와 같이 `LottoTickets`(도메인 Mode)에 의존하고있다는 의미였어요! 
(getWinningNumbers 메서드도 동일한 상황이네요!)

2024-04-07 16:39 UTC, Rok93 commented on src/main/java/domain/WinningLottoTicket.java
> +	public List<LottoWinningRank> calculateWinningRanksOfTickets(LottoTickets lottoTickets) {
`LottoGame` 객체에게 `LottoGameResult`를 계산하는 책임을 부여하겠다고 의도하신거라면 말씀하신 것처럼 생각해볼 수 있겠지만 

제가 생각한 의도는 `당첨 로또 티켓`이 로또 게임 결과를 계산하는 역할을 가지는 것이 조금 더 좋다고 생각했어요. 🙂
그 이유는 당첨 로또가 가지는 정보(메서드 파라미터로 전달받는 LottoTickets을 포함)들이 로또의 결과들을 계산할 수 있는 모든 정보를 가진다고 생각했기 때문이에요. 🤔 

이렇게된다면 `LottoGame` 객체가 굳이 필요하지 않다는 생각으로도 이어지는 것 같아요. 😃 
(사실 로또 게임 객체의 역할은 로또 게임을 진행하는 것으로 볼 수도 있고 그 게임의 진행에 따른 결과를 내는 것으로도 생각해볼 수 있을 것 같은데 네이밍만 생각해봤을 때는 어떤 책임을 가지고있을지 조금 모호한 느낌이 들어요. 🤔)

2024-04-08 02:04 UTC, Rok93 requested changes
경환님 질문주신 부분에 대해서 제 생각 남겨두었습니다.
추가적으로 잘못된 위치에 코멘트 남겨서 혼동이있으셨을 것 같아요. 🥲
이 부분들은 정정해서 코멘트 남겨두었으니 확인해서 다시 반영 부탁드릴게요. 🙏

혼동을 드려서 죄송합니다. 🙇‍♂️

2024-04-08 02:04 UTC, Rok93 commented on src/main/java/domain/WinningLottoTicket.java
> +		return lottoTickets.getLottoTickets()
잘 생각해보면 `lottoTickets`가 가진 상태를 WinningLottoTicket 객체가 직접 꺼내서 사용하고있는 것 같아요. 👀
이 또한 lottoTickets 객체에게 메시지를 보내도록 해볼 수 있겠네요. 😃

2024-04-10 14:56 UTC, skh1225 commented on src/main/java/ui/LottoView.java
> +	public static int getCountOfManualTickets() {
반영했습니다. https://github.com/next-step/java-lotto-kakao/pull/35/commits/1bc4ba317a4beea6bd05acc7e7b6f24e3be9fafa

2024-04-10 14:57 UTC, skh1225 commented on src/main/java/domain/WinningLottoTicket.java
> +	public List<LottoWinningRank> calculateWinningRanksOfTickets(LottoTickets lottoTickets) {
반영했습니다. https://github.com/next-step/java-lotto-kakao/pull/35/commits/a20031d979bedd360eb84c0c0952291140e1fc02

2024-04-10 14:57 UTC, skh1225 commented on src/main/java/domain/WinningLottoTicket.java
> +		return lottoTickets.getLottoTickets()
반영했습니다. https://github.com/next-step/java-lotto-kakao/pull/35/commits/ca33489c2dc7133ee86a901fad65ead5d126ffe6

2024-04-11 09:43 UTC, Rok93 approved these changes
경환님 피드백 반영 잘해주셨네요! 💯👍
로또 미션 이정도면 충분한 것 같아서 이만 머지하도록하겠습니다. 🎉🎉

그동안 정말 고생많으셨고, 남은 미션도 화이팅입니다. 💪💪

2024-04-11 12:06 UTC, merged