로또 2단계 미션 제출합니다.
next-step/java-lotto-kakao pull request #39
Opened 2024-04-04 09:37 UTC by riroan

안녕하세요!
이번 미션 쉽지 않네요. 수동 로또가 추가된 것으로 많은 수정이 필요했어서 확장에 약하다는 것을 느꼈습니다. 😭

2024-04-04 17:12 UTC, hyunssooo requested changes
안녕하세요. :)
몇 가지 코멘트 남겼습니다. 확인 부탁드립니다.

2024-04-04 17:12 UTC, hyunssooo commented on src/main/java/lotto/generator/RandomLottoGenerator.java
>      private static final int MAX_NUMBER = 45;
RandomLottoGenerator 잘 만들어 주셨네요. 이 부분을 추상화를 통해 LottoGenerator를 만들어 볼 수 있고 수동에 대한 구현체도 만들어 보는 것은 어떨까요?

2024-04-04 17:12 UTC, hyunssooo commented on src/main/java/lotto/domain/Money.java
https://tecoble.techcourse.co.kr/post/2020-06-11-value-object/
이 글이 도움이 되면 좋겠어요.

2024-04-04 17:12 UTC, hyunssooo commented on src/main/java/lotto/domain/Lottos.java
> +    }
외부에서 result 객체를 받아 데이터를 넣어주는 것이 아닌 내부에서 생성하고 리턴으로 해주는 것은 어떨까요?

2024-04-04 17:12 UTC, hyunssooo commented on src/main/java/lotto/domain/Lottos.java
> +    }
```java
    public void scoreLotto(Lotto lotto, WinningNumber winningNumber) {
        long answerCount = winningNumber.getWinningNumbers().getBalls().stream().filter(lotto::contain).count();
        boolean isCorrectBonusBall = lotto.contain(winningNumber.getBonusNumber());

        Ranking rank = getRank(answerCount, isCorrectBonusBall);
        addScore(rank);
    }
```

이 부분도 getter를 사용하지 않는 방법은 없을까요? WinningNumber에 lotto 를 넘겨보는 것은 어떨까요? 
Ranking 객체를 리턴할 수 있겠네요!

2024-04-04 17:12 UTC, hyunssooo commented on src/main/java/lotto/domain/Money.java
> +
사용하고 있나요?

2024-04-04 17:12 UTC, hyunssooo commented on src/main/java/lotto/domain/Lottos.java
> +
이 메서드는 view에서 사용하고 있는데요. 웹 환경이라면 해당 메서드는 호출 가능한가요? 
getter를 사용하지 말라는 말은 도메인 모델끼리 비즈니스 요구 사항을 풀어내는 경우를 말합니다. 
view에서는 getter를 사용해 데이터를 출력하는 하면 됩니다.

2024-04-07 11:55 UTC, riroan commented on src/main/java/lotto/domain/Money.java
VO는 불변성이 보장되어야하는군요!

2024-04-07 11:55 UTC, riroan commented on src/main/java/lotto/domain/Money.java
> +
다른 구현방식을 사용하려다가 수정했는데 못 지운 것 같네요 :sob:

2024-04-07 12:04 UTC, riroan commented on src/main/java/lotto/domain/Lottos.java
> +    }
오 result객체를 만들어서 반환하니 훨씬 깔끔해졌습니다.

2024-04-07 12:09 UTC, riroan commented on src/main/java/lotto/domain/Lottos.java
> +
이 코멘트는 무슨 의미인지 이해하지 못했습니다.. :thinking: 
get메소드를 view에서만 사용하기 때문에 웹에서는 사용하지 않게 되어 사라질 메소드라 지양하는 의미로 받아들였는데 마지막 줄의 getter를 사용하여 데이터를 출력하라는게 무슨 의미인지 모르겠습니다.

2024-04-07 12:10 UTC, riroan commented on src/main/java/lotto/generator/RandomLottoGenerator.java
>      private static final int MAX_NUMBER = 45;
RandomLottoGenerator는 메소드 파라미터가 없는 상태로 Lotto객체를 만들게 되는데요. 수동 로또 생성기(ManualLottoGenerator)는 메소드 파라미터에 String을 입력받아야하는데 이런 경우에도 추상화가 가능한가요?

2024-04-07 12:26 UTC, hyunssooo commented on src/main/java/lotto/generator/RandomLottoGenerator.java
>      private static final int MAX_NUMBER = 45;
메서드 파라미터가 아닌 생성자를 사용해 가능하겠네요. 🙂

```java
public interface LottoGenerator {
  Lotto generate();
}

public class RandomLottoGenerator implements LottoGenerator {

  @Override
  public Lotto generate() {
    // 구현 생략
  }
}

public class ManualLottoGenerator implements LottoGenerator {

  private final List<Integer> elements;

  public ManualLottoGenerator(List<Integer> lottoNumbers) {
    this.elements = lottoNumbers;
  }

  @Override
  public Lotto generate() {
    // elements 를 통해 구현
  }
}
```

2024-04-07 13:20 UTC, riroan commented on src/main/java/lotto/generator/RandomLottoGenerator.java
>      private static final int MAX_NUMBER = 45;
그렇다면 RandomLottoGenerator는 클래스를 한 번 생성해서 여러개의 로또를 만들 수 있었는데 ManualLottoGenerator는 한 클래스당 한개의 로또를 만들도록 구현해야할까요? 같은 인터페이스를 상속받았는데 작동방식에 이질감을 느껴 질문 드립니다!

2024-04-07 14:41 UTC, hyunssooo commented on src/main/java/lotto/generator/RandomLottoGenerator.java
>      private static final int MAX_NUMBER = 45;
이미 구현이 그렇게 되어 있어서 그렇게 느끼시는 거 아닐까요? `Generator 하나가 로또 하나를 생성한다.` 라고 하면 어색하지는 않은 것 같아요! RandomLottoGenerator 객체 생성이 많이 일어나는 것 아닐까 에 대한 고민이라면 싱글턴 패턴을 적용해 볼 수 있겠네요! 
좀 별개의 얘기긴 하지만 자바는 언어 차원에서 싱글턴을 지원하지 않는데 코틀린에서는 `object` 키워드를 통해서 싱글턴 패턴을 사용할 수도 있습니다. 🙂

2024-04-08 01:16 UTC, riroan commented on src/main/java/lotto/generator/RandomLottoGenerator.java
>      private static final int MAX_NUMBER = 45;
확실히 그런 관점으로 보면 어색하지 않네요!
그런데 싱글턴 관련해서 질문드릴게 있는데요. 싱글턴은 생성자를 private로 막아버리기 때문에 RandomLottoGenerator는 더 이상 상속이 불가능하게 되어 객체지향에 안티패턴이라는 이야기에 큰 공감을 했습니다. 여기에 대한 리뷰어님의 생각은 어떤지 궁금합니다. 

https://developer-nyong.tistory.com/29
참고했던 링크입니다!

2024-04-08 05:21 UTC, hyunssooo commented on src/main/java/lotto/generator/RandomLottoGenerator.java
>      private static final int MAX_NUMBER = 45;
엄청 많이 공부하셨군요. 👍 
저도 어느 정도 공감하고 있습니다. 비즈니스를 풀어내기 위해 객체지향 프로그래밍을 하지만 모든 걸 객체지향으로 풀어낼 수 없다고 생각합니다. 또한, 복잡도 측면에서는 절차적인 경우가 더 심플할 때도 분명 있을 거고요. `안티 패턴이야 쓰지 마` 가 아닌 상황에 맞게 사용하고 사용하지 않는 것을 판단해야 한다고 생각합니다. :) 요약하자면 제 생각은 `절대적인 건 없다. 상황에 맞는 판단을 해야 한다.` 입니다!

2024-04-08 13:56 UTC, hyunssooo requested changes
안녕하세요. 
몇 가지 추가로 코멘트 남겼습니다. 확인 부탁드려요!

2024-04-08 13:56 UTC, hyunssooo commented on src/main/java/lotto/LottoSystem.java
> +    }
일반적으로 setter는 자바빈 규약에 나오는데요. 이 부분은 제거할 수 없을까요? 

https://edu.nextstep.camp/s/MCLQmhAp/ls/DO2AJZZW

setter 메소드 사용을 자제한다.
- 인스턴스를 초기화한 후에 값을 변경할 수 있는 setter 메소드를 생성하지 않는다. 가능하면 생성자를 사용해 초기화한다.

2024-04-08 13:56 UTC, hyunssooo commented on src/main/java/lotto/LottoSystem.java
이 클래스는 패키지가 따로 분리되어 있지 않은데요. 어떤 의도일까요?

2024-04-08 13:56 UTC, hyunssooo commented on src/main/java/lotto/domain/Lottos.java
> +
https://edu.nextstep.camp/s/MCLQmhAp/ls/DO2AJZZW

젤 아래에 `getter 메소드 없이 구현 가능한가?` 를 읽어보시면 좋을 거 같아요. 
출력을 위해 DTO를 만드는 경우 getter를 사용하고 혹은 view에 도메인 객체가 나간다면 getter를 통해서 데이터를 그대로 꺼내면 된다는 의미 입니다.

2024-04-08 13:56 UTC, hyunssooo commented on src/main/java/lotto/generator/RandomLottoGenerator.java
>      private static final int MAX_NUMBER = 45;
이 부분은 도전해 보시면 좋을 것 같아요.

2024-04-08 13:56 UTC, hyunssooo commented on src/main/java/lotto/LottoApplication.java
> +            allLottos.add(lotto);
lottoSystem의 역할은 무엇인가요? 메서드들을 보니 책임이 하나인 것 같지는 않아서요.

2024-04-08 13:56 UTC, hyunssooo commented on src/main/java/lotto/domain/Result.java
winningNumber 가 Lotto 하나를 받아 Rank 객체를 리턴해도 괜찮지 않을까요? 

`WinningNumber` 는 하나의 `Lotto` 를 받아 해당 `Ranking`를 매긴다.
자연스럽지 않나요? 

이 부분은 코드로 그대로 작성할 수 있습니다. 
```java
    public long countCorrectNumbers(Lotto lotto) {
        return winningNumbers.getBalls().stream()
            .filter(lotto::contain)
            .count();
    }

    public Ranking match(Lotto lotto) {
        long count = countCorrectNumbers(lotto);
        boolean hasBonusNumber = hasBonusNumber(lotto);
        return Ranking.getRank(count, hasBonusNumber);
    }
```

2024-04-08 13:56 UTC, hyunssooo commented on src/main/java/lotto/domain/WinningNumber.java
> +    }
getter를 제거하는 방법은 없을까요? Lotto의 객체에게 메세지를 보내보면 좋을 것 같아요.

2024-04-09 05:12 UTC, riroan commented on src/main/java/lotto/domain/Result.java
이렇게 수정하니까 메소드의 책임이 확실하네요!

2024-04-15 05:02 UTC, riroan commented on src/main/java/lotto/LottoApplication.java
> +            allLottos.add(lotto);
로또플레이할 때 필요한 기능들을 모아둔 클래스입니다.

2024-04-16 08:31 UTC, riroan commented
지금까지 너무 구조화가 잘 안돼있던 감이 있어서 좀 어려웠네요.. 추가로 코멘트 달아주시면 확인해보겠습니다!

2024-04-16 15:52 UTC, hyunssooo requested changes
안녕하세요. 
몇 가지 가벼운 코멘트 남겼습니다. 
확인 부탁드립니다!
함께 고민해 보고 싶은 부분은 코멘트나 DM 으로 남겨주세요!

2024-04-16 15:52 UTC, hyunssooo commented on src/main/java/lotto/view/LottoView.java
>      public List<Integer> inputAnswer() {
이 부분은 나눠서 받으면 어떨까요? 당첨 번호 , 보너스 번호

2024-04-16 15:52 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoSystem.java
> +    }
한 리스트에 담을 필요가 있을까 해서요. index로 접근해야 하기도 하고요. 
LottoApplication 에서 바로 생성 한다면 해당 메서드는 없어도 괜찮을 것 같아요.

2024-04-16 15:52 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoSystem.java
> +    }
이 부분은 제가 의도한거랑은 조금 차이가 있는데요. 🙄

```java
List<LottoGenerator> lottoGenerators = List.of(
    new RandomLottoGenerator(),
    new RandomLottoGenerator(),
    new ManualLottoGenerator(List.of(1, 2, 3, 4, 5, 6)),
    new ManualLottoGenerator(List.of(1, 2, 3, 4, 5, 6))
);
        
new Lottos(
    lottoGenerators.stream()
        .map(it -> it.generate())
        .collect(Collectors.toList())
);
        
```

이런 느낌을 기대하긴 했어요. 작성해 주신 구조라면 다형성이 크게 의미는 없을 것 같아서요.

2024-04-16 15:52 UTC, hyunssooo commented on src/main/java/lotto/domain/Lottos.java
> +    }
```java
    public Result scoreLottos(WinningNumber winningNumber) {
        return new Result(
            values.stream()
                .map(it -> winningNumber.match(it))
                .collect(Collectors.groupingBy(it -> it, Collectors.counting()))
        );
    }
```

이런 방법도 있을 것 같아요. 

이 경우 테스트는 더 유연해 지지 않을까요? 테스트 코드는 어떻게 변경될 수 있을까요?

2024-04-16 15:52 UTC, hyunssooo commented on src/main/java/lotto/enums/Ranking.java
>      public long getReward() {
이 아래 부분을 제가 깜빡한 것 같은데요. 🥲
getReward() 분기가 꼭 필요할까요? Ranking의 필드에 존재할 수 도 있지 않을까요? 필드에 존재하면 잘 만들어둔 Money객체를 사용해 볼 수 있지 않을까요? 
value 필드는 접근제어자가 생략되었네요. 의도되었을까요?

2024-04-16 15:52 UTC, hyunssooo commented on src/main/java/lotto/generator/RandomLottoGenerator.java
>      }
싱글턴에 대해서 많이 학습하신 것 같네요!

2024-04-16 15:52 UTC, hyunssooo commented on src/main/java/lotto/generator/RandomLottoGenerator.java
>      }
```java
private static final RandomLottoGenerator instance = new RandomLottoGenerator();
``` 
으로 사용해도 괜찮지 않을까요?

2024-04-16 15:52 UTC, hyunssooo commented on src/main/java/lotto/domain/Lottos.java
> +    }
Result.reward는 필드에 꼭 필요할까요? 내부 Map 에서 계산할 수 있지 않을까요?

2024-04-16 15:52 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoSystem.java
> +    }
Result 자체에서 Profit을 리턴할 수 있지 않을까요? 
`Map<Ranking, Integer>` 각각 Ranking의 총 금액은 구할 수 있고 Map의 value를 모두 합친 값에 로또 가격을 곱하면 총 로또 금액인 것 같아서요.

2024-04-18 05:07 UTC, riroan commented on src/main/java/lotto/generator/RandomLottoGenerator.java
>      }
이렇게 사용하면 동시성이슈는 없나요? 인터넷에 검색했을 땐 동시성이슈때문에 이렇게 구현하라는 말을 들어서요.

2024-04-18 05:20 UTC, riroan commented on src/main/java/lotto/enums/Ranking.java
>      public long getReward() {
enum 사용법 숙지 이슈가 있었네요 😞 
접근제어자는 실수인 것 같습니다!

2024-04-18 05:25 UTC, riroan commented on src/main/java/lotto/domain/LottoSystem.java
> +    }
seed를 구하는 로직까지 result에 넣을 수 없을 것 같아서 살짝만 수정했습니다.

2024-04-18 05:34 UTC, riroan commented on src/main/java/lotto/domain/LottoSystem.java
> +    }
inputAnswer메소드에서 winningNumber로 만드는 작업까지 수행했습니다.

2026-02-08 22:59 UTC, closed without merging