[로또] 2단계 미션 제출합니다.
next-step/java-lotto-kakao pull request #43
Opened 2024-04-05 06:03 UTC by Eungu-Kwon

2024-04-05 12:09 UTC, shared-moon requested changes
은구님 안녕하세요!
2단계 미션 잘 진행 해 주셨네요 :)
기능은 쉽게 추가 해 주셨는데, 조금 더 살펴보면 좋을 것 같아서
피드백 확인 후 리뷰 재요청 부탁드려요!
고생 많으셨습니다 :)

2024-04-05 12:09 UTC, shared-moon commented on src/main/java/com/lotto/controller/LottoGameController.java
> +		LottoGame lottoGame = new LottoGame(money, lottoTickets, new LottoNumberGenerator());
수동 로또 갯수만큼 금액 차감을 여기서 하면 굳이 안넘겨줘도 되는거 아닐까요 ?
불필요하게 수정내역이 많아진 것 같아서요 ~

2024-04-05 12:09 UTC, shared-moon commented on src/main/java/com/lotto/model/LottoNumber.java
> +public class LottoNumber {
👍

2024-04-05 12:09 UTC, shared-moon commented on src/main/java/com/lotto/model/LottoNumber.java
> +	public static List<LottoNumber> of(List<Integer> numbers) {
요거는 약간 LottoNumbers 라는 일급 컬렉션을 만들어서 책임을 넘기는게 어떨까요 ?

2024-04-05 12:09 UTC, shared-moon commented on src/main/java/com/lotto/model/LottoRank.java
> +			.filter(lottoRank -> lottoRank.isEquals(matchCount, bonus))
👍

2024-04-05 12:09 UTC, shared-moon commented on src/main/java/com/lotto/model/LottoTickets.java
> +			LottoRank lottoRank = targetLotto.match(lottoTicket);
forEach 말고 map으로 표현하면 좀 더 깔끔하게 표현되지 않을까요 ?

```
getLottoTickets().stream()
  .map(targetLotto::match)
  .collect(Collectors.toList())
```
요런식으로 만들 수 있을 것 같아서요 ~

2024-04-11 08:29 UTC, Eungu-Kwon commented on src/main/java/com/lotto/model/LottoTickets.java
> +			LottoRank lottoRank = targetLotto.match(lottoTicket);
꼼꼼한 리뷰 감사합니다!
다시 한번 생각해볼 수 있는 기회가 되었습니다!

2024-04-11 12:47 UTC, shared-moon requested changes
은구님 안녕하세요!
피드백 반영 잘 해 주셨네요!
피드백을 조금 더 남겨 두었는데요, 요거 한번만 보고 넘어가면 좋을 것 같아요!
확인 후 리뷰 재요청 다시 한번 부탁드립니다.
고생 많으셨어요!

2024-04-11 12:47 UTC, shared-moon commented on src/main/java/com/lotto/controller/LottoGameController.java
> +		lottoGame.addManualLottoTicket(lottoTickets);
lottoTickets에 auto로 만든 티켓들을 먼저 add 하고 넘겨주는게 좋을 것 같아요!
티켓 생성의 책임을 LottoGame 밖에서 하는게 어떨까 하는 의견이었습니다 ~

2024-04-11 12:47 UTC, shared-moon commented on src/main/java/com/lotto/model/LottoNumber.java
> +			.collect(Collectors.toList()));
`Collectors.collectingAndThen()` 요런것도 있어요!

2024-04-11 12:47 UTC, shared-moon commented on src/main/java/com/lotto/model/LottoNumbers.java
> +			.collect(ArrayList::new, ArrayList::add, ArrayList::addAll);
요거 그냥 Collectors.toList 하면 안되나요 ?

2024-04-11 12:47 UTC, shared-moon commented on src/main/java/com/lotto/model/TargetLotto.java
> +			.filter(lottoTicket.getLottoNumbers().getLottoNumbersByInt()::contains)
getLottoNumbersByInt 자체도 반복문이 도는데, 그걸 계속 만들면서 List의 contains까지 하면 이 부분 이론상 성능이 최악일 것 같아요. 한번만 만들고 contains를 쓸 때는 가능한 Set을 참조하도록 바꿔보면 좋을 것 같습니다

2024-04-17 14:15 UTC, shared-moon approved these changes
은구님 안녕하세요!
피드백 반영 잘 진행 해 주셨네요 :)
여기서는 크게 피드백 드릴 내용이 없는 것 같아서 바로 머지 하도록 하겠습니다.
고생 많으셨습니다!

2024-04-17 14:15 UTC, merged