로또 2단계 미션 제출합니다.
next-step/java-lotto-kakao pull request #46
Opened 2024-04-05 06:21 UTC by HyewonKkang

변경사항
- `Lotto#getMatchCount` 추가
- [src/test/java/domain/LottoBallTest.java](https://github.com/next-step/java-lotto-kakao/pull/10/files/3d355e7726523c61466792df1343f0dc0797d488#diff-77958e31259c7dcfed4e48f04ebe6559d752bfd688ae56edf394404fd353a91c) 테스트 코드 수정
- 수동 입력 기능 추가 및 예외처리 메서드 작성

2024-04-06 11:14 UTC, hyunssooo requested changes
안녕하세요. 🙂
전체적으로 깔끔하게 잘 구현해 주셨습니다.
몇 가지 가벼운 코멘트 남겨뒀어요. 확인 부탁드립니다.
README.md 파일 업데이트는 누락된 것 같은데 이 부분도 함께 챙겨주시면 좋을 것 같아요.

2024-04-06 11:14 UTC, hyunssooo commented on src/main/java/controller/LottoGameController.java
> +        }
lottoGenerator에서 랜덤한 로또만 만들어지네요. 코드를 읽어보면 lottoGenerator 라서 헷갈릴 수 있지 않을까요? LottoGenerator를 인터페이스로 만들어 두셨는데 수동 로또에 대한 구현체도 만들어 볼 수 있지 않을까요?

2024-04-06 11:14 UTC, hyunssooo commented on src/main/java/domain/Lottos.java
`Lottos#calculateWinningResult` 

에서 stream을 사용하면 WinningResult 도 불변 객체로 만들어 볼 수 있을 것 같아요. 

```java
new WinningResult(
    lottos.stream()
        .collect(Collectors.groupingBy(winningLotto::getRank, Collectors.counting()))
);
```

2024-04-06 11:14 UTC, hyunssooo commented on src/main/java/domain/LottoMoney.java
>          this.lottoMoney = money;
`LOTTO_PRICE_UNIT` 를 사용하지 않은 이유가 있을까요?

2024-04-11 08:01 UTC, HyewonKkang commented on src/main/java/domain/LottoMoney.java
>          this.lottoMoney = money;
놓친 부분 확인해주셔서 감사합니다. 해당 상수 이용해서 수정완료했습니다! ([23503ca](https://github.com/next-step/java-lotto-kakao/pull/46/commits/23503ca28d728914fdfc466cfd33c6c6fc2f053e))

2024-04-11 08:02 UTC, HyewonKkang commented on src/main/java/controller/LottoGameController.java
> +        }
기존 변수명을 직관적으로 `randomLottoGenerator`로 수정했고, 추가적으로 `ManualLottoGenerator`를 만들어 구현했습니다 ([7b73882](https://github.com/next-step/java-lotto-kakao/pull/46/commits/7b738823d083dc7b579965fc70554362c95ddf94))

2024-04-11 08:03 UTC, HyewonKkang commented on src/main/java/domain/Lottos.java
남겨주신 코드 참고해서 불변객체로 수정완료했습니다! 좋은 의견 감사합니다 :) ([8567b83](https://github.com/next-step/java-lotto-kakao/pull/46/commits/8567b8320aa9ff17577b47eaba43139d4cd87f5a))

2024-04-12 12:43 UTC, hyunssooo approved these changes
안녕하세요.
미션 진행하신다고 고생 많으셨습니다.
몇 가지 코멘트 남겼어요. 시간 되실 때 확인 부탁드려요.
함께 고민하고 싶은 부분 있으시면 DM이나 코멘트 남겨주세요!
로또 미션 진행하신다고 고생 많으셨어요! 
좋은 주말 보내세요!

2024-04-12 12:43 UTC, hyunssooo commented on src/main/java/view/LottoGameView.java
>      }
이 부분 제가 놓쳤는데요. view에서 도메인 모델을 생성하고 있네요. 
이 부분은 어떻게 생각하시나요? 
어떤 기준으로 원시값을 리턴하고 도메인 모델을 리턴하시나요? 

개인적으로는 view에서는 원시값, 문자열, List 이 정도만 리턴하고 객체 생성은 controller에서 하고 있어요. 그리고 각각의 input 값에 대한 검증 책임이 다르다고 생각해요.

2024-04-12 12:43 UTC, hyunssooo commented on src/main/java/domain/ManualLottoGenerator.java
> +    }
요 부분은 제 의도랑 조금 다른데요. 

```java
public interface LottoGenerator {

    Lotto generate();
}

class RandomLottoGenerator implements LottoGenerator {

    @Override
    public Lotto generate() {
        // 랜덤 생성
        return new Lotto();
    }
}

class ManualLottoGenerator implements LottoGenerator {

    private final List<Integer> elements;

    public ManualLottoGenerator(List<Integer> elements) {
        this.elements = elements;
    }

    @Override
    public Lotto generate() {
        // elements를 이용해 수동 생성
        return new Lotto();
    }
}
```

이렇게 사용 가능하지 않을까 했습니다! 

```java

        List<LottoGenerator> lottoGenerators = List.of(
            new RandomLottoGenerator(),
            new RandomLottoGenerator(),
            new ManualLottoGenerator(List.of(1, 2, 3, 4, 5, 6)),
            new ManualLottoGenerator(List.of(1, 2, 3, 4, 5, 6))
        );
        
        new Lottos(
            lottoGenerators.stream()
            .map(it -> it.generate())
            .collect(Collectors.toList())
        );
    
```

2024-04-12 12:43 UTC, hyunssooo commented on src/main/java/domain/WinningResult.java
>      }
좀 복잡해 보이네요. `WinningMoney#multiply` 같은 메서드도 만들어 볼 수 있지 않을까요? 
winningMoney를 필드에 두는 것도 winningResult를 통해서 계산 가능하지 않을까 하는 생각이 드네요. 

이미 생성자로 `Map<Rank, Long>` 형태로 받고 있는데 `Map<Rank, Integer>` 형태로 다시 바꾸고 있는 이유가 있을까요? 🤔

2024-04-12 12:43 UTC, merged

2024-04-15 01:19 UTC, HyewonKkang commented on src/main/java/view/LottoGameView.java
>      }
뷰 단에서 모델을 생성해 내려주는 것 보단 말씀해주신 방법이 더 좋을 것 같습니다! 해당 내용 반영해보겠습니다 좋은 의견 감사합니다 :)

2024-04-15 01:24 UTC, HyewonKkang commented on src/main/java/domain/WinningResult.java
>      }
`WinningResult`의 타입이 `Map<Rank, Integer>`다 보니 rank와 count를 넣어주는 과정에서 Integer로 변환해주었습니다. 그리고 `sum`을 통해서 결국 long을 반환하게 된다고 생각해서 위와 같이 작성했습니다! 아래 방법으로도 가능할 것 같습니다
```java
long count = winningCounts.getOrDefault(rank, 0L);
this.winningResult.put(rank, (int) count);
```