2단계 미션 제출합니다
next-step/java-lotto-kakao pull request #56
Opened 2024-04-08 01:12 UTC by bronte000

2024-04-08 01:13 UTC, bronte000 commented
기존 PR: https://github.com/next-step/java-lotto-kakao/pull/51

2024-04-08 09:56 UTC, Rok93 requested changes
유진님 피드백 반영 잘해주셨습니다. 👍👍
남겨주신 답변도 확인했고 추가적으로 제 생각도 (현재 PR에) 남겨두었으니, 확인부탁드릴게요. 🙏
(추가적으로 의견 남겨주셔도 좋을 것 같아요!)
추가적으로 `수익률 계산 결과`가 조금 이상한 것 같은데 확인해서 수정 부탁드려요! 🙂
혹시나 어떤 부분이 문제인지 잘 모르겠다면 DM 주세요. 😉

2024-04-08 09:56 UTC, Rok93 commented on src/main/java/lotto/controller/LottoController.java
> +    }
[남겨주신 답변](https://github.com/next-step/java-lotto-kakao/pull/51/files/59366d78e5597ca624bb5b467278129056446bf5#r1555263799) 확인했습니다! 🙂
이런 도메인 로직들을 도메인 모델이 아닌 Controlelr에 두게된다면 지금 이 유효성과 동일한 로직들이 여기저기 복붙될거에요. 👀
그렇다면 추후 이 로직이 변경되게되면 일일이 확인해서 변경이 필요해지는데, 이는 실수를 유발하기가 쉬워집니다. 
자연스럽게 유지보수하기 어려운 코드가 될거에요. 🥲

가급적 이런 도메인 로직들은 도메인 모델 계층에 위치시키는 것이 좋다고 생각해요. 😃

> PurchaseAmount는 로또 구매금액이 아니라 범용적인 구매금액을 나타내는 클래스

먼저 지금 저희는 `로또 게임`이라는 도메인을 구현하고있는데 `범용적인 구매금액 객체`를 만들 이유가 있을지 한번 고민해보시면 좋을 것 같아요. 👀    [소프트웨어 개발 3대 원칙 - YAGNI](https://blog.naver.com/complusblog/221163007357)을 참고해보시면 좋을 것 같아요. 🙂


혹은 범용적인 `구매 금액 객체`를 사용하더라도 이 객체가 역할을 수행할 때, 이런 유효성 검증 로직을 넣어주는 것도 하나의 방법이 될 수 있을 것 같아요. 🤔
purchaseAmount.spend((long) manualCount * LottoTicket.PRICE);

2024-04-08 09:56 UTC, Rok93 commented on src/main/java/lotto/controller/LottoController.java
> +    public static LottoTickets buyLottoTickets(PurchaseAmount purchaseAmount, int manualCount) {
`buyLottoTickets` 메서드는 Controller 클래스 내부에서만 사용되는 것 같은데, 접근 제한자를 public으로 두신 이유가 있을까요? 👀

2024-04-08 09:56 UTC, Rok93 commented on src/main/java/lotto/controller/LottoController.java
> +        return lottoTickets;
`LottoTicketGenerator.generate(purchaseAmount)`의 결과도 `LottoTickets` 타입으로 결과를 반환하고 
LottoTickets.`add`의 결과 값을 새로운 (합치는 두 LottoTickets의 리스트들을 합친) `LottoTickets` 객체로 만들어보면 어떨까요? 🙂


추가적으로 `manualLottoTickets`, `autoLottoTickets`와 같이 네이밍을 더 명확하게해주면 코드만봐도 `lottoTickets`가 어떻게 구성되어있는지가 쉽게 파악될 것 같아요. 😉

```suggestion
        purchaseAmount.spend((long) manualCount * LottoTicket.PRICE);
        LottoTickets manualLottoTickets = Input.getManualLottoTickets(manualCount).stream()
                .map(LottoController::parseLottoTicket)
                .collect(Collectors.collectingAndThen(Collectors.toList(), LottoTickets::new));

        LottoTickets autoLottoTickets = LottoTicketGenerator.generate(purchaseAmount);
        return manualLottoTickets.add(autoLottoTickets);
```

2024-04-08 09:56 UTC, Rok93 commented on src/main/java/lotto/controller/LottoController.java
> +        Output.printResult(new LottoResultDto(lottoResult.calculateReturnRate(purchaseAmount), lottoResult.makeLottoResultMap()));
수익률 계산 결과가 이상한 것 같아요. 🤔
원인이 무엇일까요? 👀

<img width="435" alt="image" src="https://github.com/next-step/java-lotto-kakao/assets/47850258/95ea2e98-e4c5-4faf-b727-7ed3690303c4">

2024-04-08 09:56 UTC, Rok93 commented on src/main/java/lotto/model/LottoTickets.java
> +    public void add(LottoTickets additionalLottoTickets) {
현재 테스트 메서드에서만 사용하고있는 것 같아요. 🤔
테스트만을 위한 메서드라면 과감히 제거해주세요. 🙏

위에서 코멘트로 Controller에서도 add 메서드의 파라미터로 `List<LottoTicket>` 대신에 `LottoTickets`를 사용해보자고 말씀드렸으니, 만약 반영된다면 위의 메서드가 없어지겠군요? 😃

2024-04-08 09:56 UTC, Rok93 commented on src/main/java/lotto/model/PurchaseAmount.java
> +        amount -= spentAmount;
amount가 `spentAmount`보다 많은 경우에만 이 메서드 로직을 정상적으로 수행할 수 있지 않을까요? 👀

2024-04-08 09:56 UTC, Rok93 commented on src/main/java/lotto/model/LottoTicketGenerator.java
> +    private static LottoTicket generate() {
메서드와 메서드 사이에 한 줄 공백을 주면 가독성이 높아질 것 같아요. 🙂

```suggestion
    }
    
    private static LottoTicket generate() {
```

2024-04-08 09:56 UTC, Rok93 commented on src/main/java/lotto/model/LottoTicketGenerator.java
> +    public static List<LottoTicket> generate(int count) {
이 메서드는 `LottoTicketGenerator` 클래스 내부에서만 사용되는 것 같네요. 🙂
private으로 변경해주세요. 🙏

2024-04-09 02:10 UTC, bronte000 commented on src/main/java/lotto/controller/LottoController.java
> +    public static LottoTickets buyLottoTickets(PurchaseAmount purchaseAmount, int manualCount) {
변경하였습니다.

2024-04-09 02:14 UTC, bronte000 commented on src/main/java/lotto/model/LottoTicketGenerator.java
> +    private static LottoTicket generate() {
반영하였습니다.

2024-04-09 08:18 UTC, bronte000 commented on src/main/java/lotto/controller/LottoController.java
> +        Output.printResult(new LottoResultDto(lottoResult.calculateReturnRate(purchaseAmount), lottoResult.makeLottoResultMap()));
반영하였습니다.

2024-04-09 08:18 UTC, bronte000 commented on src/main/java/lotto/model/PurchaseAmount.java
> +        amount -= spentAmount;
에러 발생코드 및 관련 테스트 코드 추가하였습니다.

2024-04-09 08:19 UTC, bronte000 commented on src/main/java/lotto/model/LottoTicketGenerator.java
> +    public static List<LottoTicket> generate(int count) {
반영하였습니다.

2024-04-12 01:18 UTC, bronte000 commented on src/main/java/lotto/model/LottoTickets.java
> +    public void add(LottoTickets additionalLottoTickets) {
반영하였습니다.

2024-04-12 01:25 UTC, bronte000 commented on src/main/java/lotto/controller/LottoController.java
> +        return lottoTickets;
반영하였습니다.

2024-04-12 02:51 UTC, bronte000 commented on src/main/java/lotto/controller/LottoController.java
> +    }
YAGNI 확인해보고 PurchaseAmount를 LottoPurchaseAmount로 변경하여 해당사항 반영하였습니다.

2024-04-12 13:21 UTC, Rok93 approved these changes
유진님 피드백 반영 잘해주셨습니다. 👍💯
간단히 추가 코멘트도 남겨두었는데 가볍게 한번 확인해주시면 좋을 것 같아요. 
로또 미션은 이만 종료하도록하겠습니다. 👏👏

그동안 고생많으셨고 다음 미션도 화이팅입니다. 💪💪

2024-04-12 13:21 UTC, Rok93 commented on src/main/java/lotto/model/LottoPurchaseAmount.java
> +    private long amount;
`amount` 상태 값은 한번 할당되면 값이 변경되지 않도록 변경된 것 같네요. 😃
final 키워드를 추가해주면 좋을 것 같아요. 😉

```suggestion
    private final long amount;
```

2024-04-12 13:21 UTC, Rok93 commented on src/main/java/lotto/model/LottoTicketGenerator.java
>                  .collect(Collectors.collectingAndThen(Collectors.toList(), LottoTicket::new));
Stream을 생성할 필요 없이 바로 `Collection`의 함수인 `subLIst`를 활용해보면 어떨까요? 🙂

```suggestion
        new LottoTicket(copiedLottoNumbers.subList(0, 6))
```

2024-04-12 13:21 UTC, Rok93 commented on src/main/java/lotto/model/LottoTickets.java
> +        return this;
객체 자기 자신을 반환하는 대신에, 새로운 객체를 생성해서 반환해보면 어떨까요? 

```suggestion
    public LottoTickets add(LottoTickets additionalLottoTickets) {
        List<LottoTicket> newLottoTickets = new ArrayList<>(this.lottoTickets);
        newLottoTickets.addAll(additionalLottoTickets.lottoTickets);
        
        return new LottoTickets(newLottoTickets);
```

2024-04-12 13:22 UTC, merged

2024-04-15 01:19 UTC, bronte000 commented
남겨주신 코멘트 확인하고 반영하여 개인 브랜치에 적용해 보았습니다. 그동안 PR 도와주셔서 감사합니다.

2024-04-15 01:19 UTC, bronte000 commented
> 유진님 피드백 반영 잘해주셨습니다. 👍💯 간단히 추가 코멘트도 남겨두었는데 가볍게 한번 확인해주시면 좋을 것 같아요. 로또 미션은 이만 종료하도록하겠습니다. 👏👏
> 
> 그동안 고생많으셨고 다음 미션도 화이팅입니다. 💪💪

남겨주신 코멘트 확인하고 반영하여 개인 브랜치에 적용해 보았습니다. 그동안 PR 도와주셔서 감사합니다.