미션 Step2 제출합니다.
next-step/java-lotto-kakao pull request #61
Opened 2024-04-11 05:17 UTC by inthejim

수동 티켓 발급 기능을 추가한 step2입니다.

2024-04-12 00:45 UTC, sah3122 requested changes
2단계 미션 구현 잘해주셨습니다 👍 
몇가지 질문을 남겨두었는데 확인 부탁드려요 😄

2024-04-12 00:45 UTC, sah3122 commented on src/main/java/domain/UserManualLottos.java
> +public class UserManualLottos {
수동 로또를 별도로 분리해주신 이유가 있을까요 ? 
수동 로또는 로또의 구입(생성)방법중 하나라고 정의할수 있을것 같은데 기존 로또 객체의 생성 방법이 추가되는건 어떨까요 ?

2024-04-12 00:45 UTC, sah3122 commented on src/main/java/domain/UserManualLottos.java
> +    }
접근제어자를 package-private으로 정의한 이유가 궁금합니다 😄

2024-04-12 00:45 UTC, sah3122 commented on src/main/java/domain/LottoStore.java
> +    public LottoTickets buyRandomLottoTickets(NumberGenerator numberGenerator, int manulCount) {
클래스 내부에서 사용하는 메서드는 private 접근 제어자로 정의하여 캡슐화 하는건 어떨까요 ?

2024-04-12 00:45 UTC, sah3122 commented on src/main/java/LottoMain.java
> +        UserManualLottos.validateManualCount(lottoStore.getLottoCount(), manualCount);
수동 로또의 유효성 검사는 구입금액과 관련된 유효성 검사를 추가해보는건 어떨까요 ?

2024-04-15 00:33 UTC, inthejim commented on src/main/java/domain/UserManualLottos.java
> +public class UserManualLottos {
단순히 수동로또에 대한 유효성을 갖고 있을 객체가 필요하다고 생각하여 작성했는데,
말씀해주신대로 불필요한 것 같네요 :)
피드백 반영했습니다!

2024-04-15 00:33 UTC, inthejim commented on src/main/java/domain/UserManualLottos.java
> +    }
사실 접근제어자에 대한 개념이 명확하지 않아 사용했습니다ㅎㅎ...
package-private으로 사용하는 경우가 드물까요?

2024-04-15 08:14 UTC, sah3122 commented on src/main/java/domain/UserManualLottos.java
> +    }
제 경험으로 package-private으로 정의하는 상황은 외부로 노출하지 않기 위한 클래스를 정의할때 사용하곤합니다. 
예를들어 특정 클래스가 외부에 노출되지 않고 패키지(컨텍스트)내부에서만 의미를 가지는 경우 접근 제어자를 통해 제한할수 있습니다. 

위와같은 고민이 없는 상태라면, package-private 접근제어자를 사용하는것을 권장드리지 않습니다 😄

2024-04-15 09:13 UTC, sah3122 approved these changes
피드백 반영 잘해주셨네요 👍 
질문에 대한 답변 남겨두었는데 확인 부탁드립니다! 
로또 미션은 여기서 마무리 짓도록 하겠습니다 🙏

2024-04-15 09:13 UTC, sah3122 commented on src/main/java/domain/LottoStore.java
> +    public LottoTickets buyLottoTickets(NumberGenerator numberGenerator, List<String> userInput) {
```suggestion
    public LottoTickets buyLottoTickets(NumberGenerator numberGenerator, List<String> manualLottoNumbers) {
```
파라미터 네이밍을 조금더 의미있게 작성하면 가독성 좋은 코드가 될수 있어요 😄

2024-04-15 09:13 UTC, merged