[로또] 1단계 미션 제출합니다.
next-step/java-lotto-kakao pull request #8
Opened 2024-04-02 06:51 UTC by owenoweny

## 고민 사항

- 최대한 객체를 wrapping해보려 했습니다. 단순히 모든 것을 감싸면 복잡도가 너무 높아질 것 같다고 생각했는데, 적절한 지점을 찾는 것이 어렵다고 느꼈습니다. 
- 클래스 사이의 역할을 잘 분배하고 각각이 응집성 있게 구현하기 위해서 노력했습니다. 

위와 관련해서 피드백 주시면 감사드리겠습니다.

2024-04-03 00:26 UTC, sah3122 requested changes
안녕하세요. 로또 미션 리뷰를 맡게된 이동철 입니다 😄 
로또 미션 구현 잘해주셨습니다 👍 
몇가지 코멘트 남겨두었는데 확인 부탁드려요 🙏

2024-04-03 00:26 UTC, sah3122 commented on src/main/java/LottoConsoleView.java
> +import domains.WinningResult;
앞서 진행한 자동차 경주 미션을 참고하여 View Layer와 Domain Layer간 의존성을 제거해보는건 어떨까요 ?

2024-04-03 00:26 UTC, sah3122 commented on src/main/java/domains/Lotto.java
> +public class Lotto {
로또 클래스 정의 👍

2024-04-03 00:26 UTC, sah3122 commented on src/main/java/domains/LottoNumber.java
> +public class LottoNumber {
로또 번호를 불변객체로 잘 정의해주셨네요 👍

2024-04-03 00:26 UTC, sah3122 commented on src/main/java/utils/LottoUtils.java
> +public class LottoUtils {
개인적으론 Util 성격의 클래스를 사용하는것을 선호하지는 않지만 이처럼 도메인의 성격을 가지지 않는 상황에서는 선언해도 될것 같네요 😄 

Util 클래스임을 더 잘 나타내기 위해 객체 생성을 막아보는건 어떨까요 ?

2024-04-03 00:26 UTC, sah3122 commented on src/main/java/domains/LottoMachine.java
> +    }
로또 금액 클래스도 도출해보는건 어떨까요 ?

2024-04-03 00:26 UTC, sah3122 commented on src/main/java/domains/LottoMachine.java
> +    }
로또 기계를 통해 로또를 구입하는것은 자연스럽지만 로또 생성에 관한 로직이 로또 기계에 분산되어 있는것 같다는 생각이 드네요 😄 
로또 기계는 메시지만 던질수 있도록 정의해볼수 있지 않을까요 ?

2024-04-03 00:26 UTC, sah3122 commented on src/main/java/domains/WinningLotto.java
> +public class WinningLotto {
보너스 번호와 로또 번호가 중복될수 있을까요 ?

2024-04-03 00:26 UTC, sah3122 commented on src/main/java/domains/Lottos.java
> +    public List<WinningResult> compare(WinningLotto winningLotto) {
compare 라는 메서드명보단 `당첨 정보를 확인한다.`라는 의미를 명확하게 나타낼수 있는 네이밍을 고민해보는건 어떨까요 ?

2024-04-03 00:26 UTC, sah3122 commented on src/main/java/LottoController.java
> +        lottoConsoleView.printRevenue(lottoManager.revenueRate());
공백 라인을 활용하면 문맥을 나눌수 있고, 가독성을 높일수 있습니다 😄

2024-04-03 00:26 UTC, sah3122 commented on src/test/java/LottoMachineTest.java
> +public class LottoMachineTest {
깔끔한 테스트 코드 작성 👍 
domain 패키지에 정의한 모든 클래스에 대해 테스트 코드를 작성해보는건 어떨까요 ?

2024-04-03 05:53 UTC, owenoweny commented on src/main/java/LottoConsoleView.java
> +import domains.WinningResult;
피드백 감사합니다~ 
추가적으로, View와 Domain 사이의 의존성을 없앰으로써 얻을 수 있는 이점이 궁금합니다. DTO 객체가 만들어진다면, 결국 의존성이 view에서 DTO로 옮겨갈 뿐이라는 생각을 했습니다.

2024-04-03 06:16 UTC, owenoweny commented on src/main/java/domains/LottoMachine.java
> +    }
피드백 감사합니다~ 수정 사항 반영해봤습니다. ([beb65a0](https://github.com/next-step/java-lotto-kakao/pull/8/commits/beb65a0477f22feb51c63d94e2306fbf2af82a98))
로또 금액도 클래스로 분리함으로써 LottoMachine의 역할을 더 분리하는 장점이 있는 것 같습니다. 투입 금액을 클래스로 분리하지 않은 이유는, 도메인 클래스의 수가 이미 많아서 사용하는 클라이언트 코드(컨트롤러)에서 알아야하는 정보가 많아지고, 따라서 사용이 어려워질 것 같다고 생각했기 때문이었습니다. 이 부분에 대해서 어떻게 생각하시는지 궁금합니다.

2024-04-03 06:18 UTC, owenoweny commented on src/main/java/domains/LottoMachine.java
> +    }
> 로또 기계는 메시지만 던질수 있도록 정의해볼수 있지 않을까요 ?

메시지만 던진다는 게 어떤 형태를 생각하신 것인지 설명 부탁드려도 될까요?
처음에 저는 LottoMachine 클래스가 투입 금액을 입력받아 Lotto 객체들을 반환하는 팩토리 클래스와 비슷한 역할을 하게 하고 싶었습니다. 투입 금액을 입력받아 로또들을 만들어내는 역할이 Lottos의 역할이 아니라는 막연한 생각이 있었던 것 같습니다. 이 방식을 적용했을 때 어떤 단점이 생길까요??

2024-04-03 06:41 UTC, owenoweny commented on src/test/java/LottoMachineTest.java
> +public class LottoMachineTest {
리팩토링 과정에서 생긴 메소드 중 테스트하지 않은 것들이 있었네요 감사합니다!!

추가적으로, 객체 생성이나 단순한 파싱, 객체 변환의 역할을 하는 메소드들은 단위 테스트의 대상이 될 필요가 없다고 생각해서 작성하지 않았습니다. CI가 느려지고, 테스트 코드를 읽기 힘들게 만든다고 생각했기 때문입니다. 이와 관련해서도 의견 주시면 감사드리겠습니다.

2024-04-03 06:42 UTC, owenoweny commented
@sah3122 피드백 주신 부분 반영하고, 궁금한 점은 코멘트에 작성했습니다. 확인 및 답변 주시면 감사드리겠습니다!!

2024-04-03 14:14 UTC, sah3122 commented on src/main/java/LottoConsoleView.java
> +import domains.WinningResult;
빈약한 Domain 객체는 값만 가지고 있습니다. 이러한 도메인은 실제론 DTO 성격을 뛰게 되어 레이어간 의존성을 제거한다고 해도 큰 이점을 얻지 못할거에요. 
이번 과정을 진행하면서 빈약한 도메인을 생성하지 않고, 역할과 책임을 가지고 있는 도메인 객체를 다루는 연습을 하게됩니다. 
역할과 책임이 있다는것은 도메인 객체가 메시지를 받을수 있는 구조 라고도 볼수 있어요. 
UI Layer에서 도메인 객체에게 메시지를 던질수있다면 의도하지 않은 상황이 발생할수 있습니다. 가령 Lotto 객체가 다른 상태를 가지게 되는것이죠. 
이러한 상황을 막기 위해 domain Layer는 application Layer까지만 전달하고, UI Layer까지는 전달하지 않는 아키텍처를 가져가곤합니다 😄

2024-04-03 14:22 UTC, sah3122 commented on src/main/java/domains/LottoMachine.java
> +    }
도메인 클래스가 많아짐에 따라 비용이 증가하는것에 대해 질문 주신것 같은데 제 생각은 아래와 같습니다. 
우선 작은 단위의 클래스를 도출하는 연습을 위해 남겨드린 코멘트라고 이해해주시면 좋을것 같아요. 
작은 단위의 클래스를 도출하는 연습이 중요한 이유는 비즈니스 로직이 분산되는것을 막을수 있고, 언제나 완전한 상태의 객체를 생성할수 있기 때문입니다. 더 나아가 VO라는 개념을 학습하게되면, 의미를 부여할수 있게 됩니다. 
클라이언트 코드가 지저분해지는것과 시스템 안정성을 높이는것을 비교하자면 저는 안정성을 높이는것이 추후 비용적인 측면에서 더 큰 이점을 가질수 있을거라고 생각해요 😄

2024-04-03 14:28 UTC, sah3122 commented on src/main/java/domains/LottoMachine.java
> +    }
투입 금액을 입력 받아 로또를 생성하는것은 LottoMachine 의 역할에 어울린다고 생각해요 😄 
제가 남겨드린 코멘트의 의도는 Lotto의 생성자 로직 또는 정적 팩토리 메서드를 활용하여, `Lotto.auto()`와 같이 메시지를 던지는것을 의도하였습니다. 
현재는 자동으로 생성되는 로또 객체를 반드시 LottoMachine을 통해야 하기 때문에 다른 클래스가 자동 로또를 생성하기 위해 LottoMachine에 메시지를 던져야 하는것이죠. 
LottoMachine이 팩토리 클래스 역할을 하는것으로 정의해주신것이라면 적절하게 구현 해주셨다고 생각합니다 👍

2024-04-03 14:30 UTC, sah3122 commented on src/test/java/LottoMachineTest.java
> +public class LottoMachineTest {
도메인 패키지 하위에 생성되는 클래스는 작은 기능이라도 테스트 코드를 작성하는 편입니다. 
단위 테스트가 많아짐으로 CI가 느려진다면, 테스트 코드가 어떻게 작성되어 있는지를 우선 의심해봐야할것 같아요 😄

2024-04-04 00:06 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
남겨주신 질문에 대해 코멘트 추가해두었는데 확인 부탁드려요 ! 
다음 미션도 기대하겠습니다 😄

2024-04-04 00:06 UTC, merged